package com.ufgov.gk.common.ebay.model;

import com.ufgov.gk.common.commonbiz.model.BaseBill;

public class EbAccount extends BaseBill {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ACCOUNT.EBAY_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String ebayAccount;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ACCOUNT.EBAY_PASSWORD
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String ebayPassword;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ACCOUNT.EBAY_ACCOUNT
   *
   * @return the value of EB_ACCOUNT.EBAY_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getEbayAccount() {
    return ebayAccount;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ACCOUNT.EBAY_ACCOUNT
   *
   * @param ebayAccount the value for EB_ACCOUNT.EBAY_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setEbayAccount(String ebayAccount) {
    this.ebayAccount = ebayAccount;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ACCOUNT.EBAY_PASSWORD
   *
   * @return the value of EB_ACCOUNT.EBAY_PASSWORD
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getEbayPassword() {
    return ebayPassword;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ACCOUNT.EBAY_PASSWORD
   *
   * @param ebayPassword the value for EB_ACCOUNT.EBAY_PASSWORD
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setEbayPassword(String ebayPassword) {
    this.ebayPassword = ebayPassword;
  }
}