package com.ufgov.gk.common.ebay.model;

import com.ufgov.gk.common.commonbiz.model.BaseBill;

public class EbAppServer extends BaseBill {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_SERVER.SITE_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String siteId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_SERVER.SERVER_URL
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String serverUrl;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_SERVER.EPS_SERVER_URL
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String epsServerUrl;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_SERVER.SIGN_IN_URL
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String signInUrl;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_SERVER.SITE_ID
   *
   * @return the value of EB_APP_SERVER.SITE_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getSiteId() {
    return siteId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_SERVER.SITE_ID
   *
   * @param siteId the value for EB_APP_SERVER.SITE_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setSiteId(String siteId) {
    this.siteId = siteId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_SERVER.SERVER_URL
   *
   * @return the value of EB_APP_SERVER.SERVER_URL
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getServerUrl() {
    return serverUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_SERVER.SERVER_URL
   *
   * @param serverUrl the value for EB_APP_SERVER.SERVER_URL
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setServerUrl(String serverUrl) {
    this.serverUrl = serverUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_SERVER.EPS_SERVER_URL
   *
   * @return the value of EB_APP_SERVER.EPS_SERVER_URL
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getEpsServerUrl() {
    return epsServerUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_SERVER.EPS_SERVER_URL
   *
   * @param epsServerUrl the value for EB_APP_SERVER.EPS_SERVER_URL
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setEpsServerUrl(String epsServerUrl) {
    this.epsServerUrl = epsServerUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_SERVER.SIGN_IN_URL
   *
   * @return the value of EB_APP_SERVER.SIGN_IN_URL
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getSignInUrl() {
    return signInUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_SERVER.SIGN_IN_URL
   *
   * @param signInUrl the value for EB_APP_SERVER.SIGN_IN_URL
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setSignInUrl(String signInUrl) {
    this.signInUrl = signInUrl;
  }
}