package com.ufgov.gk.common.ebay.model;

import java.util.Date;

import com.ufgov.gk.common.commonbiz.model.BaseBill;

public class EbAppAccount extends BaseBill {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String appAccount;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.APP_PASSWORD
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String appPassword;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.PRODUCTION_DEVID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String productionDevid;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.PRODUCTION_APPID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String productionAppid;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.PRODUCTION_CERTID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String productionCertid;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.PRODUCTION_TOKEN
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String productionToken;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.EBAY_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String ebayAccount;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.CALL_LIMITATION
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Long callLimitation;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.SANDBOX_DEVID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String sandboxDevid;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.SANDBOX_APPID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String sandboxAppid;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.SANDBOX_CERTID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String sandboxCertid;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.SANDBOX_TOKEN
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String sandboxToken;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_APP_ACCOUNT.TOKEN_EXPIRE_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Date tokenExpireTime;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.APP_ACCOUNT
   *
   * @return the value of EB_APP_ACCOUNT.APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getAppAccount() {
    return appAccount;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.APP_ACCOUNT
   *
   * @param appAccount the value for EB_APP_ACCOUNT.APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setAppAccount(String appAccount) {
    this.appAccount = appAccount;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.APP_PASSWORD
   *
   * @return the value of EB_APP_ACCOUNT.APP_PASSWORD
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getAppPassword() {
    return appPassword;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.APP_PASSWORD
   *
   * @param appPassword the value for EB_APP_ACCOUNT.APP_PASSWORD
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setAppPassword(String appPassword) {
    this.appPassword = appPassword;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.PRODUCTION_DEVID
   *
   * @return the value of EB_APP_ACCOUNT.PRODUCTION_DEVID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getProductionDevid() {
    return productionDevid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.PRODUCTION_DEVID
   *
   * @param productionDevid the value for EB_APP_ACCOUNT.PRODUCTION_DEVID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setProductionDevid(String productionDevid) {
    this.productionDevid = productionDevid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.PRODUCTION_APPID
   *
   * @return the value of EB_APP_ACCOUNT.PRODUCTION_APPID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getProductionAppid() {
    return productionAppid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.PRODUCTION_APPID
   *
   * @param productionAppid the value for EB_APP_ACCOUNT.PRODUCTION_APPID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setProductionAppid(String productionAppid) {
    this.productionAppid = productionAppid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.PRODUCTION_CERTID
   *
   * @return the value of EB_APP_ACCOUNT.PRODUCTION_CERTID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getProductionCertid() {
    return productionCertid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.PRODUCTION_CERTID
   *
   * @param productionCertid the value for EB_APP_ACCOUNT.PRODUCTION_CERTID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setProductionCertid(String productionCertid) {
    this.productionCertid = productionCertid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.PRODUCTION_TOKEN
   *
   * @return the value of EB_APP_ACCOUNT.PRODUCTION_TOKEN
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getProductionToken() {
    return productionToken;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.PRODUCTION_TOKEN
   *
   * @param productionToken the value for EB_APP_ACCOUNT.PRODUCTION_TOKEN
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setProductionToken(String productionToken) {
    this.productionToken = productionToken;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.EBAY_ACCOUNT
   *
   * @return the value of EB_APP_ACCOUNT.EBAY_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getEbayAccount() {
    return ebayAccount;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.EBAY_ACCOUNT
   *
   * @param ebayAccount the value for EB_APP_ACCOUNT.EBAY_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setEbayAccount(String ebayAccount) {
    this.ebayAccount = ebayAccount;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.CALL_LIMITATION
   *
   * @return the value of EB_APP_ACCOUNT.CALL_LIMITATION
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Long getCallLimitation() {
    return callLimitation;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.CALL_LIMITATION
   *
   * @param callLimitation the value for EB_APP_ACCOUNT.CALL_LIMITATION
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setCallLimitation(Long callLimitation) {
    this.callLimitation = callLimitation;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.SANDBOX_DEVID
   *
   * @return the value of EB_APP_ACCOUNT.SANDBOX_DEVID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getSandboxDevid() {
    return sandboxDevid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.SANDBOX_DEVID
   *
   * @param sandboxDevid the value for EB_APP_ACCOUNT.SANDBOX_DEVID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setSandboxDevid(String sandboxDevid) {
    this.sandboxDevid = sandboxDevid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.SANDBOX_APPID
   *
   * @return the value of EB_APP_ACCOUNT.SANDBOX_APPID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getSandboxAppid() {
    return sandboxAppid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.SANDBOX_APPID
   *
   * @param sandboxAppid the value for EB_APP_ACCOUNT.SANDBOX_APPID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setSandboxAppid(String sandboxAppid) {
    this.sandboxAppid = sandboxAppid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.SANDBOX_CERTID
   *
   * @return the value of EB_APP_ACCOUNT.SANDBOX_CERTID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getSandboxCertid() {
    return sandboxCertid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.SANDBOX_CERTID
   *
   * @param sandboxCertid the value for EB_APP_ACCOUNT.SANDBOX_CERTID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setSandboxCertid(String sandboxCertid) {
    this.sandboxCertid = sandboxCertid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.SANDBOX_TOKEN
   *
   * @return the value of EB_APP_ACCOUNT.SANDBOX_TOKEN
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getSandboxToken() {
    return sandboxToken;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.SANDBOX_TOKEN
   *
   * @param sandboxToken the value for EB_APP_ACCOUNT.SANDBOX_TOKEN
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setSandboxToken(String sandboxToken) {
    this.sandboxToken = sandboxToken;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_APP_ACCOUNT.TOKEN_EXPIRE_TIME
   *
   * @return the value of EB_APP_ACCOUNT.TOKEN_EXPIRE_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Date getTokenExpireTime() {
    return tokenExpireTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_APP_ACCOUNT.TOKEN_EXPIRE_TIME
   *
   * @param tokenExpireTime the value for EB_APP_ACCOUNT.TOKEN_EXPIRE_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setTokenExpireTime(Date tokenExpireTime) {
    this.tokenExpireTime = tokenExpireTime;
  }
}