package com.ufgov.gk.common.ebay.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ufgov.gk.common.commonbiz.model.BaseBill;

public class EbAppAccountExample extends BaseBill {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  protected String orderByClause;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  protected List oredCriteria;

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public EbAppAccountExample() {
    oredCriteria = new ArrayList();
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  protected EbAppAccountExample(EbAppAccountExample example) {
    this.orderByClause = example.orderByClause;
    this.oredCriteria = example.oredCriteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public List getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void clear() {
    oredCriteria.clear();
  }

  /**
   * This class was generated by Abator for iBATIS.
   * This class corresponds to the database table EB_APP_ACCOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public static class Criteria {
    protected List criteriaWithoutValue;

    protected List criteriaWithSingleValue;

    protected List criteriaWithListValue;

    protected List criteriaWithBetweenValue;

    protected Criteria() {
      super();
      criteriaWithoutValue = new ArrayList();
      criteriaWithSingleValue = new ArrayList();
      criteriaWithListValue = new ArrayList();
      criteriaWithBetweenValue = new ArrayList();
    }

    public boolean isValid() {
      return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0
        || criteriaWithBetweenValue.size() > 0;
    }

    public List getCriteriaWithoutValue() {
      return criteriaWithoutValue;
    }

    public List getCriteriaWithSingleValue() {
      return criteriaWithSingleValue;
    }

    public List getCriteriaWithListValue() {
      return criteriaWithListValue;
    }

    public List getCriteriaWithBetweenValue() {
      return criteriaWithBetweenValue;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteriaWithoutValue.add(condition);
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("value", value);
      criteriaWithSingleValue.add(map);
    }

    protected void addCriterion(String condition, List values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", values);
      criteriaWithListValue.add(map);
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      List list = new ArrayList();
      list.add(value1);
      list.add(value2);
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", list);
      criteriaWithBetweenValue.add(map);
    }

    public Criteria andAppAccountIsNull() {
      addCriterion("APP_ACCOUNT is null");
      return this;
    }

    public Criteria andAppAccountIsNotNull() {
      addCriterion("APP_ACCOUNT is not null");
      return this;
    }

    public Criteria andAppAccountEqualTo(String value) {
      addCriterion("APP_ACCOUNT =", value, "appAccount");
      return this;
    }

    public Criteria andAppAccountNotEqualTo(String value) {
      addCriterion("APP_ACCOUNT <>", value, "appAccount");
      return this;
    }

    public Criteria andAppAccountGreaterThan(String value) {
      addCriterion("APP_ACCOUNT >", value, "appAccount");
      return this;
    }

    public Criteria andAppAccountGreaterThanOrEqualTo(String value) {
      addCriterion("APP_ACCOUNT >=", value, "appAccount");
      return this;
    }

    public Criteria andAppAccountLessThan(String value) {
      addCriterion("APP_ACCOUNT <", value, "appAccount");
      return this;
    }

    public Criteria andAppAccountLessThanOrEqualTo(String value) {
      addCriterion("APP_ACCOUNT <=", value, "appAccount");
      return this;
    }

    public Criteria andAppAccountLike(String value) {
      addCriterion("APP_ACCOUNT like", value, "appAccount");
      return this;
    }

    public Criteria andAppAccountNotLike(String value) {
      addCriterion("APP_ACCOUNT not like", value, "appAccount");
      return this;
    }

    public Criteria andAppAccountIn(List values) {
      addCriterion("APP_ACCOUNT in", values, "appAccount");
      return this;
    }

    public Criteria andAppAccountNotIn(List values) {
      addCriterion("APP_ACCOUNT not in", values, "appAccount");
      return this;
    }

    public Criteria andAppAccountBetween(String value1, String value2) {
      addCriterion("APP_ACCOUNT between", value1, value2, "appAccount");
      return this;
    }

    public Criteria andAppAccountNotBetween(String value1, String value2) {
      addCriterion("APP_ACCOUNT not between", value1, value2, "appAccount");
      return this;
    }

    public Criteria andAppPasswordIsNull() {
      addCriterion("APP_PASSWORD is null");
      return this;
    }

    public Criteria andAppPasswordIsNotNull() {
      addCriterion("APP_PASSWORD is not null");
      return this;
    }

    public Criteria andAppPasswordEqualTo(String value) {
      addCriterion("APP_PASSWORD =", value, "appPassword");
      return this;
    }

    public Criteria andAppPasswordNotEqualTo(String value) {
      addCriterion("APP_PASSWORD <>", value, "appPassword");
      return this;
    }

    public Criteria andAppPasswordGreaterThan(String value) {
      addCriterion("APP_PASSWORD >", value, "appPassword");
      return this;
    }

    public Criteria andAppPasswordGreaterThanOrEqualTo(String value) {
      addCriterion("APP_PASSWORD >=", value, "appPassword");
      return this;
    }

    public Criteria andAppPasswordLessThan(String value) {
      addCriterion("APP_PASSWORD <", value, "appPassword");
      return this;
    }

    public Criteria andAppPasswordLessThanOrEqualTo(String value) {
      addCriterion("APP_PASSWORD <=", value, "appPassword");
      return this;
    }

    public Criteria andAppPasswordLike(String value) {
      addCriterion("APP_PASSWORD like", value, "appPassword");
      return this;
    }

    public Criteria andAppPasswordNotLike(String value) {
      addCriterion("APP_PASSWORD not like", value, "appPassword");
      return this;
    }

    public Criteria andAppPasswordIn(List values) {
      addCriterion("APP_PASSWORD in", values, "appPassword");
      return this;
    }

    public Criteria andAppPasswordNotIn(List values) {
      addCriterion("APP_PASSWORD not in", values, "appPassword");
      return this;
    }

    public Criteria andAppPasswordBetween(String value1, String value2) {
      addCriterion("APP_PASSWORD between", value1, value2, "appPassword");
      return this;
    }

    public Criteria andAppPasswordNotBetween(String value1, String value2) {
      addCriterion("APP_PASSWORD not between", value1, value2, "appPassword");
      return this;
    }

    public Criteria andProductionDevidIsNull() {
      addCriterion("PRODUCTION_DEVID is null");
      return this;
    }

    public Criteria andProductionDevidIsNotNull() {
      addCriterion("PRODUCTION_DEVID is not null");
      return this;
    }

    public Criteria andProductionDevidEqualTo(String value) {
      addCriterion("PRODUCTION_DEVID =", value, "productionDevid");
      return this;
    }

    public Criteria andProductionDevidNotEqualTo(String value) {
      addCriterion("PRODUCTION_DEVID <>", value, "productionDevid");
      return this;
    }

    public Criteria andProductionDevidGreaterThan(String value) {
      addCriterion("PRODUCTION_DEVID >", value, "productionDevid");
      return this;
    }

    public Criteria andProductionDevidGreaterThanOrEqualTo(String value) {
      addCriterion("PRODUCTION_DEVID >=", value, "productionDevid");
      return this;
    }

    public Criteria andProductionDevidLessThan(String value) {
      addCriterion("PRODUCTION_DEVID <", value, "productionDevid");
      return this;
    }

    public Criteria andProductionDevidLessThanOrEqualTo(String value) {
      addCriterion("PRODUCTION_DEVID <=", value, "productionDevid");
      return this;
    }

    public Criteria andProductionDevidLike(String value) {
      addCriterion("PRODUCTION_DEVID like", value, "productionDevid");
      return this;
    }

    public Criteria andProductionDevidNotLike(String value) {
      addCriterion("PRODUCTION_DEVID not like", value, "productionDevid");
      return this;
    }

    public Criteria andProductionDevidIn(List values) {
      addCriterion("PRODUCTION_DEVID in", values, "productionDevid");
      return this;
    }

    public Criteria andProductionDevidNotIn(List values) {
      addCriterion("PRODUCTION_DEVID not in", values, "productionDevid");
      return this;
    }

    public Criteria andProductionDevidBetween(String value1, String value2) {
      addCriterion("PRODUCTION_DEVID between", value1, value2, "productionDevid");
      return this;
    }

    public Criteria andProductionDevidNotBetween(String value1, String value2) {
      addCriterion("PRODUCTION_DEVID not between", value1, value2, "productionDevid");
      return this;
    }

    public Criteria andProductionAppidIsNull() {
      addCriterion("PRODUCTION_APPID is null");
      return this;
    }

    public Criteria andProductionAppidIsNotNull() {
      addCriterion("PRODUCTION_APPID is not null");
      return this;
    }

    public Criteria andProductionAppidEqualTo(String value) {
      addCriterion("PRODUCTION_APPID =", value, "productionAppid");
      return this;
    }

    public Criteria andProductionAppidNotEqualTo(String value) {
      addCriterion("PRODUCTION_APPID <>", value, "productionAppid");
      return this;
    }

    public Criteria andProductionAppidGreaterThan(String value) {
      addCriterion("PRODUCTION_APPID >", value, "productionAppid");
      return this;
    }

    public Criteria andProductionAppidGreaterThanOrEqualTo(String value) {
      addCriterion("PRODUCTION_APPID >=", value, "productionAppid");
      return this;
    }

    public Criteria andProductionAppidLessThan(String value) {
      addCriterion("PRODUCTION_APPID <", value, "productionAppid");
      return this;
    }

    public Criteria andProductionAppidLessThanOrEqualTo(String value) {
      addCriterion("PRODUCTION_APPID <=", value, "productionAppid");
      return this;
    }

    public Criteria andProductionAppidLike(String value) {
      addCriterion("PRODUCTION_APPID like", value, "productionAppid");
      return this;
    }

    public Criteria andProductionAppidNotLike(String value) {
      addCriterion("PRODUCTION_APPID not like", value, "productionAppid");
      return this;
    }

    public Criteria andProductionAppidIn(List values) {
      addCriterion("PRODUCTION_APPID in", values, "productionAppid");
      return this;
    }

    public Criteria andProductionAppidNotIn(List values) {
      addCriterion("PRODUCTION_APPID not in", values, "productionAppid");
      return this;
    }

    public Criteria andProductionAppidBetween(String value1, String value2) {
      addCriterion("PRODUCTION_APPID between", value1, value2, "productionAppid");
      return this;
    }

    public Criteria andProductionAppidNotBetween(String value1, String value2) {
      addCriterion("PRODUCTION_APPID not between", value1, value2, "productionAppid");
      return this;
    }

    public Criteria andProductionCertidIsNull() {
      addCriterion("PRODUCTION_CERTID is null");
      return this;
    }

    public Criteria andProductionCertidIsNotNull() {
      addCriterion("PRODUCTION_CERTID is not null");
      return this;
    }

    public Criteria andProductionCertidEqualTo(String value) {
      addCriterion("PRODUCTION_CERTID =", value, "productionCertid");
      return this;
    }

    public Criteria andProductionCertidNotEqualTo(String value) {
      addCriterion("PRODUCTION_CERTID <>", value, "productionCertid");
      return this;
    }

    public Criteria andProductionCertidGreaterThan(String value) {
      addCriterion("PRODUCTION_CERTID >", value, "productionCertid");
      return this;
    }

    public Criteria andProductionCertidGreaterThanOrEqualTo(String value) {
      addCriterion("PRODUCTION_CERTID >=", value, "productionCertid");
      return this;
    }

    public Criteria andProductionCertidLessThan(String value) {
      addCriterion("PRODUCTION_CERTID <", value, "productionCertid");
      return this;
    }

    public Criteria andProductionCertidLessThanOrEqualTo(String value) {
      addCriterion("PRODUCTION_CERTID <=", value, "productionCertid");
      return this;
    }

    public Criteria andProductionCertidLike(String value) {
      addCriterion("PRODUCTION_CERTID like", value, "productionCertid");
      return this;
    }

    public Criteria andProductionCertidNotLike(String value) {
      addCriterion("PRODUCTION_CERTID not like", value, "productionCertid");
      return this;
    }

    public Criteria andProductionCertidIn(List values) {
      addCriterion("PRODUCTION_CERTID in", values, "productionCertid");
      return this;
    }

    public Criteria andProductionCertidNotIn(List values) {
      addCriterion("PRODUCTION_CERTID not in", values, "productionCertid");
      return this;
    }

    public Criteria andProductionCertidBetween(String value1, String value2) {
      addCriterion("PRODUCTION_CERTID between", value1, value2, "productionCertid");
      return this;
    }

    public Criteria andProductionCertidNotBetween(String value1, String value2) {
      addCriterion("PRODUCTION_CERTID not between", value1, value2, "productionCertid");
      return this;
    }

    public Criteria andProductionTokenIsNull() {
      addCriterion("PRODUCTION_TOKEN is null");
      return this;
    }

    public Criteria andProductionTokenIsNotNull() {
      addCriterion("PRODUCTION_TOKEN is not null");
      return this;
    }

    public Criteria andProductionTokenEqualTo(String value) {
      addCriterion("PRODUCTION_TOKEN =", value, "productionToken");
      return this;
    }

    public Criteria andProductionTokenNotEqualTo(String value) {
      addCriterion("PRODUCTION_TOKEN <>", value, "productionToken");
      return this;
    }

    public Criteria andProductionTokenGreaterThan(String value) {
      addCriterion("PRODUCTION_TOKEN >", value, "productionToken");
      return this;
    }

    public Criteria andProductionTokenGreaterThanOrEqualTo(String value) {
      addCriterion("PRODUCTION_TOKEN >=", value, "productionToken");
      return this;
    }

    public Criteria andProductionTokenLessThan(String value) {
      addCriterion("PRODUCTION_TOKEN <", value, "productionToken");
      return this;
    }

    public Criteria andProductionTokenLessThanOrEqualTo(String value) {
      addCriterion("PRODUCTION_TOKEN <=", value, "productionToken");
      return this;
    }

    public Criteria andProductionTokenLike(String value) {
      addCriterion("PRODUCTION_TOKEN like", value, "productionToken");
      return this;
    }

    public Criteria andProductionTokenNotLike(String value) {
      addCriterion("PRODUCTION_TOKEN not like", value, "productionToken");
      return this;
    }

    public Criteria andProductionTokenIn(List values) {
      addCriterion("PRODUCTION_TOKEN in", values, "productionToken");
      return this;
    }

    public Criteria andProductionTokenNotIn(List values) {
      addCriterion("PRODUCTION_TOKEN not in", values, "productionToken");
      return this;
    }

    public Criteria andProductionTokenBetween(String value1, String value2) {
      addCriterion("PRODUCTION_TOKEN between", value1, value2, "productionToken");
      return this;
    }

    public Criteria andProductionTokenNotBetween(String value1, String value2) {
      addCriterion("PRODUCTION_TOKEN not between", value1, value2, "productionToken");
      return this;
    }

    public Criteria andEbayAccountIsNull() {
      addCriterion("EBAY_ACCOUNT is null");
      return this;
    }

    public Criteria andEbayAccountIsNotNull() {
      addCriterion("EBAY_ACCOUNT is not null");
      return this;
    }

    public Criteria andEbayAccountEqualTo(String value) {
      addCriterion("EBAY_ACCOUNT =", value, "ebayAccount");
      return this;
    }

    public Criteria andEbayAccountNotEqualTo(String value) {
      addCriterion("EBAY_ACCOUNT <>", value, "ebayAccount");
      return this;
    }

    public Criteria andEbayAccountGreaterThan(String value) {
      addCriterion("EBAY_ACCOUNT >", value, "ebayAccount");
      return this;
    }

    public Criteria andEbayAccountGreaterThanOrEqualTo(String value) {
      addCriterion("EBAY_ACCOUNT >=", value, "ebayAccount");
      return this;
    }

    public Criteria andEbayAccountLessThan(String value) {
      addCriterion("EBAY_ACCOUNT <", value, "ebayAccount");
      return this;
    }

    public Criteria andEbayAccountLessThanOrEqualTo(String value) {
      addCriterion("EBAY_ACCOUNT <=", value, "ebayAccount");
      return this;
    }

    public Criteria andEbayAccountLike(String value) {
      addCriterion("EBAY_ACCOUNT like", value, "ebayAccount");
      return this;
    }

    public Criteria andEbayAccountNotLike(String value) {
      addCriterion("EBAY_ACCOUNT not like", value, "ebayAccount");
      return this;
    }

    public Criteria andEbayAccountIn(List values) {
      addCriterion("EBAY_ACCOUNT in", values, "ebayAccount");
      return this;
    }

    public Criteria andEbayAccountNotIn(List values) {
      addCriterion("EBAY_ACCOUNT not in", values, "ebayAccount");
      return this;
    }

    public Criteria andEbayAccountBetween(String value1, String value2) {
      addCriterion("EBAY_ACCOUNT between", value1, value2, "ebayAccount");
      return this;
    }

    public Criteria andEbayAccountNotBetween(String value1, String value2) {
      addCriterion("EBAY_ACCOUNT not between", value1, value2, "ebayAccount");
      return this;
    }

    public Criteria andCallLimitationIsNull() {
      addCriterion("CALL_LIMITATION is null");
      return this;
    }

    public Criteria andCallLimitationIsNotNull() {
      addCriterion("CALL_LIMITATION is not null");
      return this;
    }

    public Criteria andCallLimitationEqualTo(Long value) {
      addCriterion("CALL_LIMITATION =", value, "callLimitation");
      return this;
    }

    public Criteria andCallLimitationNotEqualTo(Long value) {
      addCriterion("CALL_LIMITATION <>", value, "callLimitation");
      return this;
    }

    public Criteria andCallLimitationGreaterThan(Long value) {
      addCriterion("CALL_LIMITATION >", value, "callLimitation");
      return this;
    }

    public Criteria andCallLimitationGreaterThanOrEqualTo(Long value) {
      addCriterion("CALL_LIMITATION >=", value, "callLimitation");
      return this;
    }

    public Criteria andCallLimitationLessThan(Long value) {
      addCriterion("CALL_LIMITATION <", value, "callLimitation");
      return this;
    }

    public Criteria andCallLimitationLessThanOrEqualTo(Long value) {
      addCriterion("CALL_LIMITATION <=", value, "callLimitation");
      return this;
    }

    public Criteria andCallLimitationIn(List values) {
      addCriterion("CALL_LIMITATION in", values, "callLimitation");
      return this;
    }

    public Criteria andCallLimitationNotIn(List values) {
      addCriterion("CALL_LIMITATION not in", values, "callLimitation");
      return this;
    }

    public Criteria andCallLimitationBetween(Long value1, Long value2) {
      addCriterion("CALL_LIMITATION between", value1, value2, "callLimitation");
      return this;
    }

    public Criteria andCallLimitationNotBetween(Long value1, Long value2) {
      addCriterion("CALL_LIMITATION not between", value1, value2, "callLimitation");
      return this;
    }

    public Criteria andSandboxDevidIsNull() {
      addCriterion("SANDBOX_DEVID is null");
      return this;
    }

    public Criteria andSandboxDevidIsNotNull() {
      addCriterion("SANDBOX_DEVID is not null");
      return this;
    }

    public Criteria andSandboxDevidEqualTo(String value) {
      addCriterion("SANDBOX_DEVID =", value, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxDevidNotEqualTo(String value) {
      addCriterion("SANDBOX_DEVID <>", value, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxDevidGreaterThan(String value) {
      addCriterion("SANDBOX_DEVID >", value, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxDevidGreaterThanOrEqualTo(String value) {
      addCriterion("SANDBOX_DEVID >=", value, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxDevidLessThan(String value) {
      addCriterion("SANDBOX_DEVID <", value, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxDevidLessThanOrEqualTo(String value) {
      addCriterion("SANDBOX_DEVID <=", value, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxDevidLike(String value) {
      addCriterion("SANDBOX_DEVID like", value, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxDevidNotLike(String value) {
      addCriterion("SANDBOX_DEVID not like", value, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxDevidIn(List values) {
      addCriterion("SANDBOX_DEVID in", values, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxDevidNotIn(List values) {
      addCriterion("SANDBOX_DEVID not in", values, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxDevidBetween(String value1, String value2) {
      addCriterion("SANDBOX_DEVID between", value1, value2, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxDevidNotBetween(String value1, String value2) {
      addCriterion("SANDBOX_DEVID not between", value1, value2, "sandboxDevid");
      return this;
    }

    public Criteria andSandboxAppidIsNull() {
      addCriterion("SANDBOX_APPID is null");
      return this;
    }

    public Criteria andSandboxAppidIsNotNull() {
      addCriterion("SANDBOX_APPID is not null");
      return this;
    }

    public Criteria andSandboxAppidEqualTo(String value) {
      addCriterion("SANDBOX_APPID =", value, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxAppidNotEqualTo(String value) {
      addCriterion("SANDBOX_APPID <>", value, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxAppidGreaterThan(String value) {
      addCriterion("SANDBOX_APPID >", value, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxAppidGreaterThanOrEqualTo(String value) {
      addCriterion("SANDBOX_APPID >=", value, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxAppidLessThan(String value) {
      addCriterion("SANDBOX_APPID <", value, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxAppidLessThanOrEqualTo(String value) {
      addCriterion("SANDBOX_APPID <=", value, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxAppidLike(String value) {
      addCriterion("SANDBOX_APPID like", value, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxAppidNotLike(String value) {
      addCriterion("SANDBOX_APPID not like", value, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxAppidIn(List values) {
      addCriterion("SANDBOX_APPID in", values, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxAppidNotIn(List values) {
      addCriterion("SANDBOX_APPID not in", values, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxAppidBetween(String value1, String value2) {
      addCriterion("SANDBOX_APPID between", value1, value2, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxAppidNotBetween(String value1, String value2) {
      addCriterion("SANDBOX_APPID not between", value1, value2, "sandboxAppid");
      return this;
    }

    public Criteria andSandboxCertidIsNull() {
      addCriterion("SANDBOX_CERTID is null");
      return this;
    }

    public Criteria andSandboxCertidIsNotNull() {
      addCriterion("SANDBOX_CERTID is not null");
      return this;
    }

    public Criteria andSandboxCertidEqualTo(String value) {
      addCriterion("SANDBOX_CERTID =", value, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxCertidNotEqualTo(String value) {
      addCriterion("SANDBOX_CERTID <>", value, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxCertidGreaterThan(String value) {
      addCriterion("SANDBOX_CERTID >", value, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxCertidGreaterThanOrEqualTo(String value) {
      addCriterion("SANDBOX_CERTID >=", value, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxCertidLessThan(String value) {
      addCriterion("SANDBOX_CERTID <", value, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxCertidLessThanOrEqualTo(String value) {
      addCriterion("SANDBOX_CERTID <=", value, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxCertidLike(String value) {
      addCriterion("SANDBOX_CERTID like", value, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxCertidNotLike(String value) {
      addCriterion("SANDBOX_CERTID not like", value, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxCertidIn(List values) {
      addCriterion("SANDBOX_CERTID in", values, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxCertidNotIn(List values) {
      addCriterion("SANDBOX_CERTID not in", values, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxCertidBetween(String value1, String value2) {
      addCriterion("SANDBOX_CERTID between", value1, value2, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxCertidNotBetween(String value1, String value2) {
      addCriterion("SANDBOX_CERTID not between", value1, value2, "sandboxCertid");
      return this;
    }

    public Criteria andSandboxTokenIsNull() {
      addCriterion("SANDBOX_TOKEN is null");
      return this;
    }

    public Criteria andSandboxTokenIsNotNull() {
      addCriterion("SANDBOX_TOKEN is not null");
      return this;
    }

    public Criteria andSandboxTokenEqualTo(String value) {
      addCriterion("SANDBOX_TOKEN =", value, "sandboxToken");
      return this;
    }

    public Criteria andSandboxTokenNotEqualTo(String value) {
      addCriterion("SANDBOX_TOKEN <>", value, "sandboxToken");
      return this;
    }

    public Criteria andSandboxTokenGreaterThan(String value) {
      addCriterion("SANDBOX_TOKEN >", value, "sandboxToken");
      return this;
    }

    public Criteria andSandboxTokenGreaterThanOrEqualTo(String value) {
      addCriterion("SANDBOX_TOKEN >=", value, "sandboxToken");
      return this;
    }

    public Criteria andSandboxTokenLessThan(String value) {
      addCriterion("SANDBOX_TOKEN <", value, "sandboxToken");
      return this;
    }

    public Criteria andSandboxTokenLessThanOrEqualTo(String value) {
      addCriterion("SANDBOX_TOKEN <=", value, "sandboxToken");
      return this;
    }

    public Criteria andSandboxTokenLike(String value) {
      addCriterion("SANDBOX_TOKEN like", value, "sandboxToken");
      return this;
    }

    public Criteria andSandboxTokenNotLike(String value) {
      addCriterion("SANDBOX_TOKEN not like", value, "sandboxToken");
      return this;
    }

    public Criteria andSandboxTokenIn(List values) {
      addCriterion("SANDBOX_TOKEN in", values, "sandboxToken");
      return this;
    }

    public Criteria andSandboxTokenNotIn(List values) {
      addCriterion("SANDBOX_TOKEN not in", values, "sandboxToken");
      return this;
    }

    public Criteria andSandboxTokenBetween(String value1, String value2) {
      addCriterion("SANDBOX_TOKEN between", value1, value2, "sandboxToken");
      return this;
    }

    public Criteria andSandboxTokenNotBetween(String value1, String value2) {
      addCriterion("SANDBOX_TOKEN not between", value1, value2, "sandboxToken");
      return this;
    }

    public Criteria andTokenExpireTimeIsNull() {
      addCriterion("TOKEN_EXPIRE_TIME is null");
      return this;
    }

    public Criteria andTokenExpireTimeIsNotNull() {
      addCriterion("TOKEN_EXPIRE_TIME is not null");
      return this;
    }

    public Criteria andTokenExpireTimeEqualTo(Date value) {
      addCriterion("TOKEN_EXPIRE_TIME =", value, "tokenExpireTime");
      return this;
    }

    public Criteria andTokenExpireTimeNotEqualTo(Date value) {
      addCriterion("TOKEN_EXPIRE_TIME <>", value, "tokenExpireTime");
      return this;
    }

    public Criteria andTokenExpireTimeGreaterThan(Date value) {
      addCriterion("TOKEN_EXPIRE_TIME >", value, "tokenExpireTime");
      return this;
    }

    public Criteria andTokenExpireTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("TOKEN_EXPIRE_TIME >=", value, "tokenExpireTime");
      return this;
    }

    public Criteria andTokenExpireTimeLessThan(Date value) {
      addCriterion("TOKEN_EXPIRE_TIME <", value, "tokenExpireTime");
      return this;
    }

    public Criteria andTokenExpireTimeLessThanOrEqualTo(Date value) {
      addCriterion("TOKEN_EXPIRE_TIME <=", value, "tokenExpireTime");
      return this;
    }

    public Criteria andTokenExpireTimeIn(List values) {
      addCriterion("TOKEN_EXPIRE_TIME in", values, "tokenExpireTime");
      return this;
    }

    public Criteria andTokenExpireTimeNotIn(List values) {
      addCriterion("TOKEN_EXPIRE_TIME not in", values, "tokenExpireTime");
      return this;
    }

    public Criteria andTokenExpireTimeBetween(Date value1, Date value2) {
      addCriterion("TOKEN_EXPIRE_TIME between", value1, value2, "tokenExpireTime");
      return this;
    }

    public Criteria andTokenExpireTimeNotBetween(Date value1, Date value2) {
      addCriterion("TOKEN_EXPIRE_TIME not between", value1, value2, "tokenExpireTime");
      return this;
    }
  }
}