package com.ufgov.gk.common.ebay.model;

import com.ufgov.gk.common.commonbiz.model.BaseBill;

public class EbCategory extends BaseBill {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CATEGORY.CATEGORY_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String categoryId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CATEGORY.CATEGORY_NAME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String categoryName;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CATEGORY.PARENT_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String parentId;

  private String parentName;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CATEGORY.CATEGORY_ID
   *
   * @return the value of EB_CATEGORY.CATEGORY_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getCategoryId() {
    return categoryId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CATEGORY.CATEGORY_ID
   *
   * @param categoryId the value for EB_CATEGORY.CATEGORY_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CATEGORY.CATEGORY_NAME
   *
   * @return the value of EB_CATEGORY.CATEGORY_NAME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getCategoryName() {
    return categoryName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CATEGORY.CATEGORY_NAME
   *
   * @param categoryName the value for EB_CATEGORY.CATEGORY_NAME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CATEGORY.PARENT_ID
   *
   * @return the value of EB_CATEGORY.PARENT_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getParentId() {
    return parentId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CATEGORY.PARENT_ID
   *
   * @param parentId the value for EB_CATEGORY.PARENT_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setParentId(String parentId) {
    this.parentId = parentId;
  }

  public String getParentName() {
    return parentName;
  }

  public void setParentName(String parentName) {
    this.parentName = parentName;
  }
}