package com.ufgov.gk.common.ebay.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.ufgov.gk.common.commonbiz.model.BaseBill;

public class EbCandidateItem extends BaseBill {
  public static final String STATUS_CANDIDATE = "0"; //候选

  public static final String STATUS_RECOMMEND = "1"; //推荐

  public static final String STATUS_SELLING = "2"; //销售中

  public static final String STATUS_VERY_RECOMMEND = "3"; //强烈推荐

  public static final String STATUS_CHEAP_FOR_SALE = "5";//便宜冲量

  public static final String STATUS_SELECTED_BY_COMPUTER = "6";//计算机自动计算推荐的

  private String imageUrl;

  private BigDecimal transportFee;

  private List<EbCandidateItemRef2> candidateItemRefLst = new ArrayList<EbCandidateItemRef2>();

  private String sku;

  //ebay 物品 种类，用于计算ebay费用
  private String categoryType;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.CANDIDATE_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String candidateId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.CATEGORY_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String categoryId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.NAME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String name;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.WEIGHT
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private BigDecimal weight;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.ITEM_SIZE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String itemSize;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.TB_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String tbUrl;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.TB_PRICE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private BigDecimal tbPrice;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.TB_REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String tbRemark;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.EB_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String ebUrl;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.EB_PRICE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private BigDecimal ebPrice;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.EB_SOLD_QUALITY
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private Long ebSoldQuality;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.EB_REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String ebRemark;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.TB_SHIPPING_FEE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private BigDecimal tbShippingFee;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String remark;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.STATUS
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String status;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.CURRENCY_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String currencyId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.TB_FULL_NAME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String tbFullName;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.EB_FULL_NAME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String ebFullName;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.EB_SHIPPING_FEE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private BigDecimal ebShippingFee;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.ALI_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String aliUrl;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.ALI_PRICE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private BigDecimal aliPrice;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.ALI_REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String aliRemark;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.EB_SITE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String ebSite;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.ITEM_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String itemId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.START_TIME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private Date startTime;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.END_TIME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private Date endTime;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.IS_SELLING
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String isSelling;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.SELLING_PER_DAY
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private BigDecimal sellingPerDay;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.SELLING_DAYS
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private Long sellingDays;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.COST
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private BigDecimal cost;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.PROFIT
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private BigDecimal profit;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.PROFIT_RATE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private BigDecimal profitRate;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.EB_IMAGE_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String ebImageUrl;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_CANDIDATE_ITEM.TRANSPORT_MODE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  private String transportMode;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.CANDIDATE_ID
   *
   * @return the value of EB_CANDIDATE_ITEM.CANDIDATE_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getCandidateId() {
    return candidateId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.CANDIDATE_ID
   *
   * @param candidateId the value for EB_CANDIDATE_ITEM.CANDIDATE_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setCandidateId(String candidateId) {
    this.candidateId = candidateId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.CATEGORY_ID
   *
   * @return the value of EB_CANDIDATE_ITEM.CATEGORY_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getCategoryId() {
    return categoryId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.CATEGORY_ID
   *
   * @param categoryId the value for EB_CANDIDATE_ITEM.CATEGORY_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.NAME
   *
   * @return the value of EB_CANDIDATE_ITEM.NAME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.NAME
   *
   * @param name the value for EB_CANDIDATE_ITEM.NAME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.WEIGHT
   *
   * @return the value of EB_CANDIDATE_ITEM.WEIGHT
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public BigDecimal getWeight() {
    return weight;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.WEIGHT
   *
   * @param weight the value for EB_CANDIDATE_ITEM.WEIGHT
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setWeight(BigDecimal weight) {
    this.weight = weight;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.ITEM_SIZE
   *
   * @return the value of EB_CANDIDATE_ITEM.ITEM_SIZE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getItemSize() {
    return itemSize;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.ITEM_SIZE
   *
   * @param itemSize the value for EB_CANDIDATE_ITEM.ITEM_SIZE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setItemSize(String itemSize) {
    this.itemSize = itemSize;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.TB_URL
   *
   * @return the value of EB_CANDIDATE_ITEM.TB_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getTbUrl() {
    return tbUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.TB_URL
   *
   * @param tbUrl the value for EB_CANDIDATE_ITEM.TB_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setTbUrl(String tbUrl) {
    this.tbUrl = tbUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.TB_PRICE
   *
   * @return the value of EB_CANDIDATE_ITEM.TB_PRICE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public BigDecimal getTbPrice() {
    return tbPrice;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.TB_PRICE
   *
   * @param tbPrice the value for EB_CANDIDATE_ITEM.TB_PRICE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setTbPrice(BigDecimal tbPrice) {
    this.tbPrice = tbPrice;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.TB_REMARK
   *
   * @return the value of EB_CANDIDATE_ITEM.TB_REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getTbRemark() {
    return tbRemark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.TB_REMARK
   *
   * @param tbRemark the value for EB_CANDIDATE_ITEM.TB_REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setTbRemark(String tbRemark) {
    this.tbRemark = tbRemark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.EB_URL
   *
   * @return the value of EB_CANDIDATE_ITEM.EB_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getEbUrl() {
    return ebUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.EB_URL
   *
   * @param ebUrl the value for EB_CANDIDATE_ITEM.EB_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setEbUrl(String ebUrl) {
    this.ebUrl = ebUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.EB_PRICE
   *
   * @return the value of EB_CANDIDATE_ITEM.EB_PRICE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public BigDecimal getEbPrice() {
    return ebPrice;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.EB_PRICE
   *
   * @param ebPrice the value for EB_CANDIDATE_ITEM.EB_PRICE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setEbPrice(BigDecimal ebPrice) {
    this.ebPrice = ebPrice;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.EB_SOLD_QUALITY
   *
   * @return the value of EB_CANDIDATE_ITEM.EB_SOLD_QUALITY
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public Long getEbSoldQuality() {
    return ebSoldQuality;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.EB_SOLD_QUALITY
   *
   * @param ebSoldQuality the value for EB_CANDIDATE_ITEM.EB_SOLD_QUALITY
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setEbSoldQuality(Long ebSoldQuality) {
    this.ebSoldQuality = ebSoldQuality;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.EB_REMARK
   *
   * @return the value of EB_CANDIDATE_ITEM.EB_REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getEbRemark() {
    return ebRemark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.EB_REMARK
   *
   * @param ebRemark the value for EB_CANDIDATE_ITEM.EB_REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setEbRemark(String ebRemark) {
    this.ebRemark = ebRemark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.TB_SHIPPING_FEE
   *
   * @return the value of EB_CANDIDATE_ITEM.TB_SHIPPING_FEE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public BigDecimal getTbShippingFee() {
    return tbShippingFee;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.TB_SHIPPING_FEE
   *
   * @param tbShippingFee the value for EB_CANDIDATE_ITEM.TB_SHIPPING_FEE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setTbShippingFee(BigDecimal tbShippingFee) {
    this.tbShippingFee = tbShippingFee;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.REMARK
   *
   * @return the value of EB_CANDIDATE_ITEM.REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getRemark() {
    return remark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.REMARK
   *
   * @param remark the value for EB_CANDIDATE_ITEM.REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setRemark(String remark) {
    this.remark = remark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.STATUS
   *
   * @return the value of EB_CANDIDATE_ITEM.STATUS
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getStatus() {
    return status;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.STATUS
   *
   * @param status the value for EB_CANDIDATE_ITEM.STATUS
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.CURRENCY_ID
   *
   * @return the value of EB_CANDIDATE_ITEM.CURRENCY_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getCurrencyId() {
    return currencyId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.CURRENCY_ID
   *
   * @param currencyId the value for EB_CANDIDATE_ITEM.CURRENCY_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setCurrencyId(String currencyId) {
    this.currencyId = currencyId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.TB_FULL_NAME
   *
   * @return the value of EB_CANDIDATE_ITEM.TB_FULL_NAME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getTbFullName() {
    return tbFullName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.TB_FULL_NAME
   *
   * @param tbFullName the value for EB_CANDIDATE_ITEM.TB_FULL_NAME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setTbFullName(String tbFullName) {
    this.tbFullName = tbFullName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.EB_FULL_NAME
   *
   * @return the value of EB_CANDIDATE_ITEM.EB_FULL_NAME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getEbFullName() {
    return ebFullName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.EB_FULL_NAME
   *
   * @param ebFullName the value for EB_CANDIDATE_ITEM.EB_FULL_NAME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setEbFullName(String ebFullName) {
    this.ebFullName = ebFullName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.EB_SHIPPING_FEE
   *
   * @return the value of EB_CANDIDATE_ITEM.EB_SHIPPING_FEE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public BigDecimal getEbShippingFee() {
    return ebShippingFee;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.EB_SHIPPING_FEE
   *
   * @param ebShippingFee the value for EB_CANDIDATE_ITEM.EB_SHIPPING_FEE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setEbShippingFee(BigDecimal ebShippingFee) {
    this.ebShippingFee = ebShippingFee;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.ALI_URL
   *
   * @return the value of EB_CANDIDATE_ITEM.ALI_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getAliUrl() {
    return aliUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.ALI_URL
   *
   * @param aliUrl the value for EB_CANDIDATE_ITEM.ALI_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setAliUrl(String aliUrl) {
    this.aliUrl = aliUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.ALI_PRICE
   *
   * @return the value of EB_CANDIDATE_ITEM.ALI_PRICE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public BigDecimal getAliPrice() {
    return aliPrice;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.ALI_PRICE
   *
   * @param aliPrice the value for EB_CANDIDATE_ITEM.ALI_PRICE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setAliPrice(BigDecimal aliPrice) {
    this.aliPrice = aliPrice;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.ALI_REMARK
   *
   * @return the value of EB_CANDIDATE_ITEM.ALI_REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getAliRemark() {
    return aliRemark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.ALI_REMARK
   *
   * @param aliRemark the value for EB_CANDIDATE_ITEM.ALI_REMARK
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setAliRemark(String aliRemark) {
    this.aliRemark = aliRemark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.EB_SITE
   *
   * @return the value of EB_CANDIDATE_ITEM.EB_SITE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getEbSite() {
    return ebSite;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.EB_SITE
   *
   * @param ebSite the value for EB_CANDIDATE_ITEM.EB_SITE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setEbSite(String ebSite) {
    this.ebSite = ebSite;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.ITEM_ID
   *
   * @return the value of EB_CANDIDATE_ITEM.ITEM_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getItemId() {
    return itemId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.ITEM_ID
   *
   * @param itemId the value for EB_CANDIDATE_ITEM.ITEM_ID
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setItemId(String itemId) {
    this.itemId = itemId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.START_TIME
   *
   * @return the value of EB_CANDIDATE_ITEM.START_TIME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public Date getStartTime() {
    return startTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.START_TIME
   *
   * @param startTime the value for EB_CANDIDATE_ITEM.START_TIME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setStartTime(Date startTime) {
    this.startTime = startTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.END_TIME
   *
   * @return the value of EB_CANDIDATE_ITEM.END_TIME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public Date getEndTime() {
    return endTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.END_TIME
   *
   * @param endTime the value for EB_CANDIDATE_ITEM.END_TIME
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setEndTime(Date endTime) {
    this.endTime = endTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.IS_SELLING
   *
   * @return the value of EB_CANDIDATE_ITEM.IS_SELLING
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getIsSelling() {
    return isSelling;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.IS_SELLING
   *
   * @param isSelling the value for EB_CANDIDATE_ITEM.IS_SELLING
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setIsSelling(String isSelling) {
    this.isSelling = isSelling;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.SELLING_PER_DAY
   *
   * @return the value of EB_CANDIDATE_ITEM.SELLING_PER_DAY
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public BigDecimal getSellingPerDay() {
    return sellingPerDay;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.SELLING_PER_DAY
   *
   * @param sellingPerDay the value for EB_CANDIDATE_ITEM.SELLING_PER_DAY
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setSellingPerDay(BigDecimal sellingPerDay) {
    this.sellingPerDay = sellingPerDay;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.SELLING_DAYS
   *
   * @return the value of EB_CANDIDATE_ITEM.SELLING_DAYS
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public Long getSellingDays() {
    return sellingDays;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.SELLING_DAYS
   *
   * @param sellingDays the value for EB_CANDIDATE_ITEM.SELLING_DAYS
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setSellingDays(Long sellingDays) {
    this.sellingDays = sellingDays;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.COST
   *
   * @return the value of EB_CANDIDATE_ITEM.COST
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public BigDecimal getCost() {
    return cost;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.COST
   *
   * @param cost the value for EB_CANDIDATE_ITEM.COST
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.PROFIT
   *
   * @return the value of EB_CANDIDATE_ITEM.PROFIT
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public BigDecimal getProfit() {
    return profit;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.PROFIT
   *
   * @param profit the value for EB_CANDIDATE_ITEM.PROFIT
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setProfit(BigDecimal profit) {
    this.profit = profit;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.PROFIT_RATE
   *
   * @return the value of EB_CANDIDATE_ITEM.PROFIT_RATE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public BigDecimal getProfitRate() {
    return profitRate;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.PROFIT_RATE
   *
   * @param profitRate the value for EB_CANDIDATE_ITEM.PROFIT_RATE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setProfitRate(BigDecimal profitRate) {
    this.profitRate = profitRate;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.EB_IMAGE_URL
   *
   * @return the value of EB_CANDIDATE_ITEM.EB_IMAGE_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getEbImageUrl() {
    return ebImageUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.EB_IMAGE_URL
   *
   * @param ebImageUrl the value for EB_CANDIDATE_ITEM.EB_IMAGE_URL
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setEbImageUrl(String ebImageUrl) {
    this.ebImageUrl = ebImageUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_CANDIDATE_ITEM.TRANSPORT_MODE
   *
   * @return the value of EB_CANDIDATE_ITEM.TRANSPORT_MODE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getTransportMode() {
    return transportMode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_CANDIDATE_ITEM.TRANSPORT_MODE
   *
   * @param transportMode the value for EB_CANDIDATE_ITEM.TRANSPORT_MODE
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setTransportMode(String transportMode) {
    this.transportMode = transportMode;
  }

  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public BigDecimal getTransportFee() {
    return transportFee;
  }

  public void setTransportFee(BigDecimal transportFee) {
    this.transportFee = transportFee;
  }

  public List<EbCandidateItemRef2> getCandidateItemRefLst() {
    return candidateItemRefLst;
  }

  public void setCandidateItemRefLst(List<EbCandidateItemRef2> candidateItemRefLst) {
    this.candidateItemRefLst = candidateItemRefLst;
  }

  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }

  public String getCategoryType() {
    return categoryType;
  }

  public void setCategoryType(String categoryType) {
    this.categoryType = categoryType;
  }

}