package com.ufgov.gk.common.ebay.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EbCandidateItemExample {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  protected String orderByClause;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  protected List oredCriteria;

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public EbCandidateItemExample() {
    oredCriteria = new ArrayList();
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  protected EbCandidateItemExample(EbCandidateItemExample example) {
    this.orderByClause = example.orderByClause;
    this.oredCriteria = example.oredCriteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public List getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public void clear() {
    oredCriteria.clear();
  }

  /**
   * This class was generated by Abator for iBATIS.
   * This class corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  public static class Criteria {
    protected List criteriaWithoutValue;

    protected List criteriaWithSingleValue;

    protected List criteriaWithListValue;

    protected List criteriaWithBetweenValue;

    protected Criteria() {
      super();
      criteriaWithoutValue = new ArrayList();
      criteriaWithSingleValue = new ArrayList();
      criteriaWithListValue = new ArrayList();
      criteriaWithBetweenValue = new ArrayList();
    }

    public boolean isValid() {
      return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0
        || criteriaWithBetweenValue.size() > 0;
    }

    public List getCriteriaWithoutValue() {
      return criteriaWithoutValue;
    }

    public List getCriteriaWithSingleValue() {
      return criteriaWithSingleValue;
    }

    public List getCriteriaWithListValue() {
      return criteriaWithListValue;
    }

    public List getCriteriaWithBetweenValue() {
      return criteriaWithBetweenValue;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteriaWithoutValue.add(condition);
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("value", value);
      criteriaWithSingleValue.add(map);
    }

    protected void addCriterion(String condition, List values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", values);
      criteriaWithListValue.add(map);
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      List list = new ArrayList();
      list.add(value1);
      list.add(value2);
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", list);
      criteriaWithBetweenValue.add(map);
    }

    public Criteria andCandidateIdIsNull() {
      addCriterion("CANDIDATE_ID is null");
      return this;
    }

    public Criteria andCandidateIdIsNotNull() {
      addCriterion("CANDIDATE_ID is not null");
      return this;
    }

    public Criteria andCandidateIdEqualTo(String value) {
      addCriterion("CANDIDATE_ID =", value, "candidateId");
      return this;
    }

    public Criteria andCandidateIdNotEqualTo(String value) {
      addCriterion("CANDIDATE_ID <>", value, "candidateId");
      return this;
    }

    public Criteria andCandidateIdGreaterThan(String value) {
      addCriterion("CANDIDATE_ID >", value, "candidateId");
      return this;
    }

    public Criteria andCandidateIdGreaterThanOrEqualTo(String value) {
      addCriterion("CANDIDATE_ID >=", value, "candidateId");
      return this;
    }

    public Criteria andCandidateIdLessThan(String value) {
      addCriterion("CANDIDATE_ID <", value, "candidateId");
      return this;
    }

    public Criteria andCandidateIdLessThanOrEqualTo(String value) {
      addCriterion("CANDIDATE_ID <=", value, "candidateId");
      return this;
    }

    public Criteria andCandidateIdLike(String value) {
      addCriterion("CANDIDATE_ID like", value, "candidateId");
      return this;
    }

    public Criteria andCandidateIdNotLike(String value) {
      addCriterion("CANDIDATE_ID not like", value, "candidateId");
      return this;
    }

    public Criteria andCandidateIdIn(List values) {
      addCriterion("CANDIDATE_ID in", values, "candidateId");
      return this;
    }

    public Criteria andCandidateIdNotIn(List values) {
      addCriterion("CANDIDATE_ID not in", values, "candidateId");
      return this;
    }

    public Criteria andCandidateIdBetween(String value1, String value2) {
      addCriterion("CANDIDATE_ID between", value1, value2, "candidateId");
      return this;
    }

    public Criteria andCandidateIdNotBetween(String value1, String value2) {
      addCriterion("CANDIDATE_ID not between", value1, value2, "candidateId");
      return this;
    }

    public Criteria andCategoryIdIsNull() {
      addCriterion("CATEGORY_ID is null");
      return this;
    }

    public Criteria andCategoryIdIsNotNull() {
      addCriterion("CATEGORY_ID is not null");
      return this;
    }

    public Criteria andCategoryIdEqualTo(String value) {
      addCriterion("CATEGORY_ID =", value, "categoryId");
      return this;
    }

    public Criteria andCategoryIdNotEqualTo(String value) {
      addCriterion("CATEGORY_ID <>", value, "categoryId");
      return this;
    }

    public Criteria andCategoryIdGreaterThan(String value) {
      addCriterion("CATEGORY_ID >", value, "categoryId");
      return this;
    }

    public Criteria andCategoryIdGreaterThanOrEqualTo(String value) {
      addCriterion("CATEGORY_ID >=", value, "categoryId");
      return this;
    }

    public Criteria andCategoryIdLessThan(String value) {
      addCriterion("CATEGORY_ID <", value, "categoryId");
      return this;
    }

    public Criteria andCategoryIdLessThanOrEqualTo(String value) {
      addCriterion("CATEGORY_ID <=", value, "categoryId");
      return this;
    }

    public Criteria andCategoryIdLike(String value) {
      addCriterion("CATEGORY_ID like", value, "categoryId");
      return this;
    }

    public Criteria andCategoryIdNotLike(String value) {
      addCriterion("CATEGORY_ID not like", value, "categoryId");
      return this;
    }

    public Criteria andCategoryIdIn(List values) {
      addCriterion("CATEGORY_ID in", values, "categoryId");
      return this;
    }

    public Criteria andCategoryIdNotIn(List values) {
      addCriterion("CATEGORY_ID not in", values, "categoryId");
      return this;
    }

    public Criteria andCategoryIdBetween(String value1, String value2) {
      addCriterion("CATEGORY_ID between", value1, value2, "categoryId");
      return this;
    }

    public Criteria andCategoryIdNotBetween(String value1, String value2) {
      addCriterion("CATEGORY_ID not between", value1, value2, "categoryId");
      return this;
    }

    public Criteria andNameIsNull() {
      addCriterion("NAME is null");
      return this;
    }

    public Criteria andNameIsNotNull() {
      addCriterion("NAME is not null");
      return this;
    }

    public Criteria andNameEqualTo(String value) {
      addCriterion("NAME =", value, "name");
      return this;
    }

    public Criteria andNameNotEqualTo(String value) {
      addCriterion("NAME <>", value, "name");
      return this;
    }

    public Criteria andNameGreaterThan(String value) {
      addCriterion("NAME >", value, "name");
      return this;
    }

    public Criteria andNameGreaterThanOrEqualTo(String value) {
      addCriterion("NAME >=", value, "name");
      return this;
    }

    public Criteria andNameLessThan(String value) {
      addCriterion("NAME <", value, "name");
      return this;
    }

    public Criteria andNameLessThanOrEqualTo(String value) {
      addCriterion("NAME <=", value, "name");
      return this;
    }

    public Criteria andNameLike(String value) {
      addCriterion("NAME like", value, "name");
      return this;
    }

    public Criteria andNameNotLike(String value) {
      addCriterion("NAME not like", value, "name");
      return this;
    }

    public Criteria andNameIn(List values) {
      addCriterion("NAME in", values, "name");
      return this;
    }

    public Criteria andNameNotIn(List values) {
      addCriterion("NAME not in", values, "name");
      return this;
    }

    public Criteria andNameBetween(String value1, String value2) {
      addCriterion("NAME between", value1, value2, "name");
      return this;
    }

    public Criteria andNameNotBetween(String value1, String value2) {
      addCriterion("NAME not between", value1, value2, "name");
      return this;
    }

    public Criteria andWeightIsNull() {
      addCriterion("WEIGHT is null");
      return this;
    }

    public Criteria andWeightIsNotNull() {
      addCriterion("WEIGHT is not null");
      return this;
    }

    public Criteria andWeightEqualTo(BigDecimal value) {
      addCriterion("WEIGHT =", value, "weight");
      return this;
    }

    public Criteria andWeightNotEqualTo(BigDecimal value) {
      addCriterion("WEIGHT <>", value, "weight");
      return this;
    }

    public Criteria andWeightGreaterThan(BigDecimal value) {
      addCriterion("WEIGHT >", value, "weight");
      return this;
    }

    public Criteria andWeightGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("WEIGHT >=", value, "weight");
      return this;
    }

    public Criteria andWeightLessThan(BigDecimal value) {
      addCriterion("WEIGHT <", value, "weight");
      return this;
    }

    public Criteria andWeightLessThanOrEqualTo(BigDecimal value) {
      addCriterion("WEIGHT <=", value, "weight");
      return this;
    }

    public Criteria andWeightIn(List values) {
      addCriterion("WEIGHT in", values, "weight");
      return this;
    }

    public Criteria andWeightNotIn(List values) {
      addCriterion("WEIGHT not in", values, "weight");
      return this;
    }

    public Criteria andWeightBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("WEIGHT between", value1, value2, "weight");
      return this;
    }

    public Criteria andWeightNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("WEIGHT not between", value1, value2, "weight");
      return this;
    }

    public Criteria andItemSizeIsNull() {
      addCriterion("ITEM_SIZE is null");
      return this;
    }

    public Criteria andItemSizeIsNotNull() {
      addCriterion("ITEM_SIZE is not null");
      return this;
    }

    public Criteria andItemSizeEqualTo(String value) {
      addCriterion("ITEM_SIZE =", value, "itemSize");
      return this;
    }

    public Criteria andItemSizeNotEqualTo(String value) {
      addCriterion("ITEM_SIZE <>", value, "itemSize");
      return this;
    }

    public Criteria andItemSizeGreaterThan(String value) {
      addCriterion("ITEM_SIZE >", value, "itemSize");
      return this;
    }

    public Criteria andItemSizeGreaterThanOrEqualTo(String value) {
      addCriterion("ITEM_SIZE >=", value, "itemSize");
      return this;
    }

    public Criteria andItemSizeLessThan(String value) {
      addCriterion("ITEM_SIZE <", value, "itemSize");
      return this;
    }

    public Criteria andItemSizeLessThanOrEqualTo(String value) {
      addCriterion("ITEM_SIZE <=", value, "itemSize");
      return this;
    }

    public Criteria andItemSizeLike(String value) {
      addCriterion("ITEM_SIZE like", value, "itemSize");
      return this;
    }

    public Criteria andItemSizeNotLike(String value) {
      addCriterion("ITEM_SIZE not like", value, "itemSize");
      return this;
    }

    public Criteria andItemSizeIn(List values) {
      addCriterion("ITEM_SIZE in", values, "itemSize");
      return this;
    }

    public Criteria andItemSizeNotIn(List values) {
      addCriterion("ITEM_SIZE not in", values, "itemSize");
      return this;
    }

    public Criteria andItemSizeBetween(String value1, String value2) {
      addCriterion("ITEM_SIZE between", value1, value2, "itemSize");
      return this;
    }

    public Criteria andItemSizeNotBetween(String value1, String value2) {
      addCriterion("ITEM_SIZE not between", value1, value2, "itemSize");
      return this;
    }

    public Criteria andTbUrlIsNull() {
      addCriterion("TB_URL is null");
      return this;
    }

    public Criteria andTbUrlIsNotNull() {
      addCriterion("TB_URL is not null");
      return this;
    }

    public Criteria andTbUrlEqualTo(String value) {
      addCriterion("TB_URL =", value, "tbUrl");
      return this;
    }

    public Criteria andTbUrlNotEqualTo(String value) {
      addCriterion("TB_URL <>", value, "tbUrl");
      return this;
    }

    public Criteria andTbUrlGreaterThan(String value) {
      addCriterion("TB_URL >", value, "tbUrl");
      return this;
    }

    public Criteria andTbUrlGreaterThanOrEqualTo(String value) {
      addCriterion("TB_URL >=", value, "tbUrl");
      return this;
    }

    public Criteria andTbUrlLessThan(String value) {
      addCriterion("TB_URL <", value, "tbUrl");
      return this;
    }

    public Criteria andTbUrlLessThanOrEqualTo(String value) {
      addCriterion("TB_URL <=", value, "tbUrl");
      return this;
    }

    public Criteria andTbUrlLike(String value) {
      addCriterion("TB_URL like", value, "tbUrl");
      return this;
    }

    public Criteria andTbUrlNotLike(String value) {
      addCriterion("TB_URL not like", value, "tbUrl");
      return this;
    }

    public Criteria andTbUrlIn(List values) {
      addCriterion("TB_URL in", values, "tbUrl");
      return this;
    }

    public Criteria andTbUrlNotIn(List values) {
      addCriterion("TB_URL not in", values, "tbUrl");
      return this;
    }

    public Criteria andTbUrlBetween(String value1, String value2) {
      addCriterion("TB_URL between", value1, value2, "tbUrl");
      return this;
    }

    public Criteria andTbUrlNotBetween(String value1, String value2) {
      addCriterion("TB_URL not between", value1, value2, "tbUrl");
      return this;
    }

    public Criteria andTbPriceIsNull() {
      addCriterion("TB_PRICE is null");
      return this;
    }

    public Criteria andTbPriceIsNotNull() {
      addCriterion("TB_PRICE is not null");
      return this;
    }

    public Criteria andTbPriceEqualTo(BigDecimal value) {
      addCriterion("TB_PRICE =", value, "tbPrice");
      return this;
    }

    public Criteria andTbPriceNotEqualTo(BigDecimal value) {
      addCriterion("TB_PRICE <>", value, "tbPrice");
      return this;
    }

    public Criteria andTbPriceGreaterThan(BigDecimal value) {
      addCriterion("TB_PRICE >", value, "tbPrice");
      return this;
    }

    public Criteria andTbPriceGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("TB_PRICE >=", value, "tbPrice");
      return this;
    }

    public Criteria andTbPriceLessThan(BigDecimal value) {
      addCriterion("TB_PRICE <", value, "tbPrice");
      return this;
    }

    public Criteria andTbPriceLessThanOrEqualTo(BigDecimal value) {
      addCriterion("TB_PRICE <=", value, "tbPrice");
      return this;
    }

    public Criteria andTbPriceIn(List values) {
      addCriterion("TB_PRICE in", values, "tbPrice");
      return this;
    }

    public Criteria andTbPriceNotIn(List values) {
      addCriterion("TB_PRICE not in", values, "tbPrice");
      return this;
    }

    public Criteria andTbPriceBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("TB_PRICE between", value1, value2, "tbPrice");
      return this;
    }

    public Criteria andTbPriceNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("TB_PRICE not between", value1, value2, "tbPrice");
      return this;
    }

    public Criteria andTbRemarkIsNull() {
      addCriterion("TB_REMARK is null");
      return this;
    }

    public Criteria andTbRemarkIsNotNull() {
      addCriterion("TB_REMARK is not null");
      return this;
    }

    public Criteria andTbRemarkEqualTo(String value) {
      addCriterion("TB_REMARK =", value, "tbRemark");
      return this;
    }

    public Criteria andTbRemarkNotEqualTo(String value) {
      addCriterion("TB_REMARK <>", value, "tbRemark");
      return this;
    }

    public Criteria andTbRemarkGreaterThan(String value) {
      addCriterion("TB_REMARK >", value, "tbRemark");
      return this;
    }

    public Criteria andTbRemarkGreaterThanOrEqualTo(String value) {
      addCriterion("TB_REMARK >=", value, "tbRemark");
      return this;
    }

    public Criteria andTbRemarkLessThan(String value) {
      addCriterion("TB_REMARK <", value, "tbRemark");
      return this;
    }

    public Criteria andTbRemarkLessThanOrEqualTo(String value) {
      addCriterion("TB_REMARK <=", value, "tbRemark");
      return this;
    }

    public Criteria andTbRemarkLike(String value) {
      addCriterion("TB_REMARK like", value, "tbRemark");
      return this;
    }

    public Criteria andTbRemarkNotLike(String value) {
      addCriterion("TB_REMARK not like", value, "tbRemark");
      return this;
    }

    public Criteria andTbRemarkIn(List values) {
      addCriterion("TB_REMARK in", values, "tbRemark");
      return this;
    }

    public Criteria andTbRemarkNotIn(List values) {
      addCriterion("TB_REMARK not in", values, "tbRemark");
      return this;
    }

    public Criteria andTbRemarkBetween(String value1, String value2) {
      addCriterion("TB_REMARK between", value1, value2, "tbRemark");
      return this;
    }

    public Criteria andTbRemarkNotBetween(String value1, String value2) {
      addCriterion("TB_REMARK not between", value1, value2, "tbRemark");
      return this;
    }

    public Criteria andEbUrlIsNull() {
      addCriterion("EB_URL is null");
      return this;
    }

    public Criteria andEbUrlIsNotNull() {
      addCriterion("EB_URL is not null");
      return this;
    }

    public Criteria andEbUrlEqualTo(String value) {
      addCriterion("EB_URL =", value, "ebUrl");
      return this;
    }

    public Criteria andEbUrlNotEqualTo(String value) {
      addCriterion("EB_URL <>", value, "ebUrl");
      return this;
    }

    public Criteria andEbUrlGreaterThan(String value) {
      addCriterion("EB_URL >", value, "ebUrl");
      return this;
    }

    public Criteria andEbUrlGreaterThanOrEqualTo(String value) {
      addCriterion("EB_URL >=", value, "ebUrl");
      return this;
    }

    public Criteria andEbUrlLessThan(String value) {
      addCriterion("EB_URL <", value, "ebUrl");
      return this;
    }

    public Criteria andEbUrlLessThanOrEqualTo(String value) {
      addCriterion("EB_URL <=", value, "ebUrl");
      return this;
    }

    public Criteria andEbUrlLike(String value) {
      addCriterion("EB_URL like", value, "ebUrl");
      return this;
    }

    public Criteria andEbUrlNotLike(String value) {
      addCriterion("EB_URL not like", value, "ebUrl");
      return this;
    }

    public Criteria andEbUrlIn(List values) {
      addCriterion("EB_URL in", values, "ebUrl");
      return this;
    }

    public Criteria andEbUrlNotIn(List values) {
      addCriterion("EB_URL not in", values, "ebUrl");
      return this;
    }

    public Criteria andEbUrlBetween(String value1, String value2) {
      addCriterion("EB_URL between", value1, value2, "ebUrl");
      return this;
    }

    public Criteria andEbUrlNotBetween(String value1, String value2) {
      addCriterion("EB_URL not between", value1, value2, "ebUrl");
      return this;
    }

    public Criteria andEbPriceIsNull() {
      addCriterion("EB_PRICE is null");
      return this;
    }

    public Criteria andEbPriceIsNotNull() {
      addCriterion("EB_PRICE is not null");
      return this;
    }

    public Criteria andEbPriceEqualTo(BigDecimal value) {
      addCriterion("EB_PRICE =", value, "ebPrice");
      return this;
    }

    public Criteria andEbPriceNotEqualTo(BigDecimal value) {
      addCriterion("EB_PRICE <>", value, "ebPrice");
      return this;
    }

    public Criteria andEbPriceGreaterThan(BigDecimal value) {
      addCriterion("EB_PRICE >", value, "ebPrice");
      return this;
    }

    public Criteria andEbPriceGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("EB_PRICE >=", value, "ebPrice");
      return this;
    }

    public Criteria andEbPriceLessThan(BigDecimal value) {
      addCriterion("EB_PRICE <", value, "ebPrice");
      return this;
    }

    public Criteria andEbPriceLessThanOrEqualTo(BigDecimal value) {
      addCriterion("EB_PRICE <=", value, "ebPrice");
      return this;
    }

    public Criteria andEbPriceIn(List values) {
      addCriterion("EB_PRICE in", values, "ebPrice");
      return this;
    }

    public Criteria andEbPriceNotIn(List values) {
      addCriterion("EB_PRICE not in", values, "ebPrice");
      return this;
    }

    public Criteria andEbPriceBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("EB_PRICE between", value1, value2, "ebPrice");
      return this;
    }

    public Criteria andEbPriceNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("EB_PRICE not between", value1, value2, "ebPrice");
      return this;
    }

    public Criteria andEbSoldQualityIsNull() {
      addCriterion("EB_SOLD_QUALITY is null");
      return this;
    }

    public Criteria andEbSoldQualityIsNotNull() {
      addCriterion("EB_SOLD_QUALITY is not null");
      return this;
    }

    public Criteria andEbSoldQualityEqualTo(Long value) {
      addCriterion("EB_SOLD_QUALITY =", value, "ebSoldQuality");
      return this;
    }

    public Criteria andEbSoldQualityNotEqualTo(Long value) {
      addCriterion("EB_SOLD_QUALITY <>", value, "ebSoldQuality");
      return this;
    }

    public Criteria andEbSoldQualityGreaterThan(Long value) {
      addCriterion("EB_SOLD_QUALITY >", value, "ebSoldQuality");
      return this;
    }

    public Criteria andEbSoldQualityGreaterThanOrEqualTo(Long value) {
      addCriterion("EB_SOLD_QUALITY >=", value, "ebSoldQuality");
      return this;
    }

    public Criteria andEbSoldQualityLessThan(Long value) {
      addCriterion("EB_SOLD_QUALITY <", value, "ebSoldQuality");
      return this;
    }

    public Criteria andEbSoldQualityLessThanOrEqualTo(Long value) {
      addCriterion("EB_SOLD_QUALITY <=", value, "ebSoldQuality");
      return this;
    }

    public Criteria andEbSoldQualityIn(List values) {
      addCriterion("EB_SOLD_QUALITY in", values, "ebSoldQuality");
      return this;
    }

    public Criteria andEbSoldQualityNotIn(List values) {
      addCriterion("EB_SOLD_QUALITY not in", values, "ebSoldQuality");
      return this;
    }

    public Criteria andEbSoldQualityBetween(Long value1, Long value2) {
      addCriterion("EB_SOLD_QUALITY between", value1, value2, "ebSoldQuality");
      return this;
    }

    public Criteria andEbSoldQualityNotBetween(Long value1, Long value2) {
      addCriterion("EB_SOLD_QUALITY not between", value1, value2, "ebSoldQuality");
      return this;
    }

    public Criteria andEbRemarkIsNull() {
      addCriterion("EB_REMARK is null");
      return this;
    }

    public Criteria andEbRemarkIsNotNull() {
      addCriterion("EB_REMARK is not null");
      return this;
    }

    public Criteria andEbRemarkEqualTo(String value) {
      addCriterion("EB_REMARK =", value, "ebRemark");
      return this;
    }

    public Criteria andEbRemarkNotEqualTo(String value) {
      addCriterion("EB_REMARK <>", value, "ebRemark");
      return this;
    }

    public Criteria andEbRemarkGreaterThan(String value) {
      addCriterion("EB_REMARK >", value, "ebRemark");
      return this;
    }

    public Criteria andEbRemarkGreaterThanOrEqualTo(String value) {
      addCriterion("EB_REMARK >=", value, "ebRemark");
      return this;
    }

    public Criteria andEbRemarkLessThan(String value) {
      addCriterion("EB_REMARK <", value, "ebRemark");
      return this;
    }

    public Criteria andEbRemarkLessThanOrEqualTo(String value) {
      addCriterion("EB_REMARK <=", value, "ebRemark");
      return this;
    }

    public Criteria andEbRemarkLike(String value) {
      addCriterion("EB_REMARK like", value, "ebRemark");
      return this;
    }

    public Criteria andEbRemarkNotLike(String value) {
      addCriterion("EB_REMARK not like", value, "ebRemark");
      return this;
    }

    public Criteria andEbRemarkIn(List values) {
      addCriterion("EB_REMARK in", values, "ebRemark");
      return this;
    }

    public Criteria andEbRemarkNotIn(List values) {
      addCriterion("EB_REMARK not in", values, "ebRemark");
      return this;
    }

    public Criteria andEbRemarkBetween(String value1, String value2) {
      addCriterion("EB_REMARK between", value1, value2, "ebRemark");
      return this;
    }

    public Criteria andEbRemarkNotBetween(String value1, String value2) {
      addCriterion("EB_REMARK not between", value1, value2, "ebRemark");
      return this;
    }

    public Criteria andTbShippingFeeIsNull() {
      addCriterion("TB_SHIPPING_FEE is null");
      return this;
    }

    public Criteria andTbShippingFeeIsNotNull() {
      addCriterion("TB_SHIPPING_FEE is not null");
      return this;
    }

    public Criteria andTbShippingFeeEqualTo(BigDecimal value) {
      addCriterion("TB_SHIPPING_FEE =", value, "tbShippingFee");
      return this;
    }

    public Criteria andTbShippingFeeNotEqualTo(BigDecimal value) {
      addCriterion("TB_SHIPPING_FEE <>", value, "tbShippingFee");
      return this;
    }

    public Criteria andTbShippingFeeGreaterThan(BigDecimal value) {
      addCriterion("TB_SHIPPING_FEE >", value, "tbShippingFee");
      return this;
    }

    public Criteria andTbShippingFeeGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("TB_SHIPPING_FEE >=", value, "tbShippingFee");
      return this;
    }

    public Criteria andTbShippingFeeLessThan(BigDecimal value) {
      addCriterion("TB_SHIPPING_FEE <", value, "tbShippingFee");
      return this;
    }

    public Criteria andTbShippingFeeLessThanOrEqualTo(BigDecimal value) {
      addCriterion("TB_SHIPPING_FEE <=", value, "tbShippingFee");
      return this;
    }

    public Criteria andTbShippingFeeIn(List values) {
      addCriterion("TB_SHIPPING_FEE in", values, "tbShippingFee");
      return this;
    }

    public Criteria andTbShippingFeeNotIn(List values) {
      addCriterion("TB_SHIPPING_FEE not in", values, "tbShippingFee");
      return this;
    }

    public Criteria andTbShippingFeeBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("TB_SHIPPING_FEE between", value1, value2, "tbShippingFee");
      return this;
    }

    public Criteria andTbShippingFeeNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("TB_SHIPPING_FEE not between", value1, value2, "tbShippingFee");
      return this;
    }

    public Criteria andRemarkIsNull() {
      addCriterion("REMARK is null");
      return this;
    }

    public Criteria andRemarkIsNotNull() {
      addCriterion("REMARK is not null");
      return this;
    }

    public Criteria andRemarkEqualTo(String value) {
      addCriterion("REMARK =", value, "remark");
      return this;
    }

    public Criteria andRemarkNotEqualTo(String value) {
      addCriterion("REMARK <>", value, "remark");
      return this;
    }

    public Criteria andRemarkGreaterThan(String value) {
      addCriterion("REMARK >", value, "remark");
      return this;
    }

    public Criteria andRemarkGreaterThanOrEqualTo(String value) {
      addCriterion("REMARK >=", value, "remark");
      return this;
    }

    public Criteria andRemarkLessThan(String value) {
      addCriterion("REMARK <", value, "remark");
      return this;
    }

    public Criteria andRemarkLessThanOrEqualTo(String value) {
      addCriterion("REMARK <=", value, "remark");
      return this;
    }

    public Criteria andRemarkLike(String value) {
      addCriterion("REMARK like", value, "remark");
      return this;
    }

    public Criteria andRemarkNotLike(String value) {
      addCriterion("REMARK not like", value, "remark");
      return this;
    }

    public Criteria andRemarkIn(List values) {
      addCriterion("REMARK in", values, "remark");
      return this;
    }

    public Criteria andRemarkNotIn(List values) {
      addCriterion("REMARK not in", values, "remark");
      return this;
    }

    public Criteria andRemarkBetween(String value1, String value2) {
      addCriterion("REMARK between", value1, value2, "remark");
      return this;
    }

    public Criteria andRemarkNotBetween(String value1, String value2) {
      addCriterion("REMARK not between", value1, value2, "remark");
      return this;
    }

    public Criteria andStatusIsNull() {
      addCriterion("STATUS is null");
      return this;
    }

    public Criteria andStatusIsNotNull() {
      addCriterion("STATUS is not null");
      return this;
    }

    public Criteria andStatusEqualTo(String value) {
      addCriterion("STATUS =", value, "status");
      return this;
    }

    public Criteria andStatusNotEqualTo(String value) {
      addCriterion("STATUS <>", value, "status");
      return this;
    }

    public Criteria andStatusGreaterThan(String value) {
      addCriterion("STATUS >", value, "status");
      return this;
    }

    public Criteria andStatusGreaterThanOrEqualTo(String value) {
      addCriterion("STATUS >=", value, "status");
      return this;
    }

    public Criteria andStatusLessThan(String value) {
      addCriterion("STATUS <", value, "status");
      return this;
    }

    public Criteria andStatusLessThanOrEqualTo(String value) {
      addCriterion("STATUS <=", value, "status");
      return this;
    }

    public Criteria andStatusLike(String value) {
      addCriterion("STATUS like", value, "status");
      return this;
    }

    public Criteria andStatusNotLike(String value) {
      addCriterion("STATUS not like", value, "status");
      return this;
    }

    public Criteria andStatusIn(List values) {
      addCriterion("STATUS in", values, "status");
      return this;
    }

    public Criteria andStatusNotIn(List values) {
      addCriterion("STATUS not in", values, "status");
      return this;
    }

    public Criteria andStatusBetween(String value1, String value2) {
      addCriterion("STATUS between", value1, value2, "status");
      return this;
    }

    public Criteria andStatusNotBetween(String value1, String value2) {
      addCriterion("STATUS not between", value1, value2, "status");
      return this;
    }

    public Criteria andCurrencyIdIsNull() {
      addCriterion("CURRENCY_ID is null");
      return this;
    }

    public Criteria andCurrencyIdIsNotNull() {
      addCriterion("CURRENCY_ID is not null");
      return this;
    }

    public Criteria andCurrencyIdEqualTo(String value) {
      addCriterion("CURRENCY_ID =", value, "currencyId");
      return this;
    }

    public Criteria andCurrencyIdNotEqualTo(String value) {
      addCriterion("CURRENCY_ID <>", value, "currencyId");
      return this;
    }

    public Criteria andCurrencyIdGreaterThan(String value) {
      addCriterion("CURRENCY_ID >", value, "currencyId");
      return this;
    }

    public Criteria andCurrencyIdGreaterThanOrEqualTo(String value) {
      addCriterion("CURRENCY_ID >=", value, "currencyId");
      return this;
    }

    public Criteria andCurrencyIdLessThan(String value) {
      addCriterion("CURRENCY_ID <", value, "currencyId");
      return this;
    }

    public Criteria andCurrencyIdLessThanOrEqualTo(String value) {
      addCriterion("CURRENCY_ID <=", value, "currencyId");
      return this;
    }

    public Criteria andCurrencyIdLike(String value) {
      addCriterion("CURRENCY_ID like", value, "currencyId");
      return this;
    }

    public Criteria andCurrencyIdNotLike(String value) {
      addCriterion("CURRENCY_ID not like", value, "currencyId");
      return this;
    }

    public Criteria andCurrencyIdIn(List values) {
      addCriterion("CURRENCY_ID in", values, "currencyId");
      return this;
    }

    public Criteria andCurrencyIdNotIn(List values) {
      addCriterion("CURRENCY_ID not in", values, "currencyId");
      return this;
    }

    public Criteria andCurrencyIdBetween(String value1, String value2) {
      addCriterion("CURRENCY_ID between", value1, value2, "currencyId");
      return this;
    }

    public Criteria andCurrencyIdNotBetween(String value1, String value2) {
      addCriterion("CURRENCY_ID not between", value1, value2, "currencyId");
      return this;
    }

    public Criteria andTbFullNameIsNull() {
      addCriterion("TB_FULL_NAME is null");
      return this;
    }

    public Criteria andTbFullNameIsNotNull() {
      addCriterion("TB_FULL_NAME is not null");
      return this;
    }

    public Criteria andTbFullNameEqualTo(String value) {
      addCriterion("TB_FULL_NAME =", value, "tbFullName");
      return this;
    }

    public Criteria andTbFullNameNotEqualTo(String value) {
      addCriterion("TB_FULL_NAME <>", value, "tbFullName");
      return this;
    }

    public Criteria andTbFullNameGreaterThan(String value) {
      addCriterion("TB_FULL_NAME >", value, "tbFullName");
      return this;
    }

    public Criteria andTbFullNameGreaterThanOrEqualTo(String value) {
      addCriterion("TB_FULL_NAME >=", value, "tbFullName");
      return this;
    }

    public Criteria andTbFullNameLessThan(String value) {
      addCriterion("TB_FULL_NAME <", value, "tbFullName");
      return this;
    }

    public Criteria andTbFullNameLessThanOrEqualTo(String value) {
      addCriterion("TB_FULL_NAME <=", value, "tbFullName");
      return this;
    }

    public Criteria andTbFullNameLike(String value) {
      addCriterion("TB_FULL_NAME like", value, "tbFullName");
      return this;
    }

    public Criteria andTbFullNameNotLike(String value) {
      addCriterion("TB_FULL_NAME not like", value, "tbFullName");
      return this;
    }

    public Criteria andTbFullNameIn(List values) {
      addCriterion("TB_FULL_NAME in", values, "tbFullName");
      return this;
    }

    public Criteria andTbFullNameNotIn(List values) {
      addCriterion("TB_FULL_NAME not in", values, "tbFullName");
      return this;
    }

    public Criteria andTbFullNameBetween(String value1, String value2) {
      addCriterion("TB_FULL_NAME between", value1, value2, "tbFullName");
      return this;
    }

    public Criteria andTbFullNameNotBetween(String value1, String value2) {
      addCriterion("TB_FULL_NAME not between", value1, value2, "tbFullName");
      return this;
    }

    public Criteria andEbFullNameIsNull() {
      addCriterion("EB_FULL_NAME is null");
      return this;
    }

    public Criteria andEbFullNameIsNotNull() {
      addCriterion("EB_FULL_NAME is not null");
      return this;
    }

    public Criteria andEbFullNameEqualTo(String value) {
      addCriterion("EB_FULL_NAME =", value, "ebFullName");
      return this;
    }

    public Criteria andEbFullNameNotEqualTo(String value) {
      addCriterion("EB_FULL_NAME <>", value, "ebFullName");
      return this;
    }

    public Criteria andEbFullNameGreaterThan(String value) {
      addCriterion("EB_FULL_NAME >", value, "ebFullName");
      return this;
    }

    public Criteria andEbFullNameGreaterThanOrEqualTo(String value) {
      addCriterion("EB_FULL_NAME >=", value, "ebFullName");
      return this;
    }

    public Criteria andEbFullNameLessThan(String value) {
      addCriterion("EB_FULL_NAME <", value, "ebFullName");
      return this;
    }

    public Criteria andEbFullNameLessThanOrEqualTo(String value) {
      addCriterion("EB_FULL_NAME <=", value, "ebFullName");
      return this;
    }

    public Criteria andEbFullNameLike(String value) {
      addCriterion("EB_FULL_NAME like", value, "ebFullName");
      return this;
    }

    public Criteria andEbFullNameNotLike(String value) {
      addCriterion("EB_FULL_NAME not like", value, "ebFullName");
      return this;
    }

    public Criteria andEbFullNameIn(List values) {
      addCriterion("EB_FULL_NAME in", values, "ebFullName");
      return this;
    }

    public Criteria andEbFullNameNotIn(List values) {
      addCriterion("EB_FULL_NAME not in", values, "ebFullName");
      return this;
    }

    public Criteria andEbFullNameBetween(String value1, String value2) {
      addCriterion("EB_FULL_NAME between", value1, value2, "ebFullName");
      return this;
    }

    public Criteria andEbFullNameNotBetween(String value1, String value2) {
      addCriterion("EB_FULL_NAME not between", value1, value2, "ebFullName");
      return this;
    }

    public Criteria andEbShippingFeeIsNull() {
      addCriterion("EB_SHIPPING_FEE is null");
      return this;
    }

    public Criteria andEbShippingFeeIsNotNull() {
      addCriterion("EB_SHIPPING_FEE is not null");
      return this;
    }

    public Criteria andEbShippingFeeEqualTo(BigDecimal value) {
      addCriterion("EB_SHIPPING_FEE =", value, "ebShippingFee");
      return this;
    }

    public Criteria andEbShippingFeeNotEqualTo(BigDecimal value) {
      addCriterion("EB_SHIPPING_FEE <>", value, "ebShippingFee");
      return this;
    }

    public Criteria andEbShippingFeeGreaterThan(BigDecimal value) {
      addCriterion("EB_SHIPPING_FEE >", value, "ebShippingFee");
      return this;
    }

    public Criteria andEbShippingFeeGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("EB_SHIPPING_FEE >=", value, "ebShippingFee");
      return this;
    }

    public Criteria andEbShippingFeeLessThan(BigDecimal value) {
      addCriterion("EB_SHIPPING_FEE <", value, "ebShippingFee");
      return this;
    }

    public Criteria andEbShippingFeeLessThanOrEqualTo(BigDecimal value) {
      addCriterion("EB_SHIPPING_FEE <=", value, "ebShippingFee");
      return this;
    }

    public Criteria andEbShippingFeeIn(List values) {
      addCriterion("EB_SHIPPING_FEE in", values, "ebShippingFee");
      return this;
    }

    public Criteria andEbShippingFeeNotIn(List values) {
      addCriterion("EB_SHIPPING_FEE not in", values, "ebShippingFee");
      return this;
    }

    public Criteria andEbShippingFeeBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("EB_SHIPPING_FEE between", value1, value2, "ebShippingFee");
      return this;
    }

    public Criteria andEbShippingFeeNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("EB_SHIPPING_FEE not between", value1, value2, "ebShippingFee");
      return this;
    }

    public Criteria andAliUrlIsNull() {
      addCriterion("ALI_URL is null");
      return this;
    }

    public Criteria andAliUrlIsNotNull() {
      addCriterion("ALI_URL is not null");
      return this;
    }

    public Criteria andAliUrlEqualTo(String value) {
      addCriterion("ALI_URL =", value, "aliUrl");
      return this;
    }

    public Criteria andAliUrlNotEqualTo(String value) {
      addCriterion("ALI_URL <>", value, "aliUrl");
      return this;
    }

    public Criteria andAliUrlGreaterThan(String value) {
      addCriterion("ALI_URL >", value, "aliUrl");
      return this;
    }

    public Criteria andAliUrlGreaterThanOrEqualTo(String value) {
      addCriterion("ALI_URL >=", value, "aliUrl");
      return this;
    }

    public Criteria andAliUrlLessThan(String value) {
      addCriterion("ALI_URL <", value, "aliUrl");
      return this;
    }

    public Criteria andAliUrlLessThanOrEqualTo(String value) {
      addCriterion("ALI_URL <=", value, "aliUrl");
      return this;
    }

    public Criteria andAliUrlLike(String value) {
      addCriterion("ALI_URL like", value, "aliUrl");
      return this;
    }

    public Criteria andAliUrlNotLike(String value) {
      addCriterion("ALI_URL not like", value, "aliUrl");
      return this;
    }

    public Criteria andAliUrlIn(List values) {
      addCriterion("ALI_URL in", values, "aliUrl");
      return this;
    }

    public Criteria andAliUrlNotIn(List values) {
      addCriterion("ALI_URL not in", values, "aliUrl");
      return this;
    }

    public Criteria andAliUrlBetween(String value1, String value2) {
      addCriterion("ALI_URL between", value1, value2, "aliUrl");
      return this;
    }

    public Criteria andAliUrlNotBetween(String value1, String value2) {
      addCriterion("ALI_URL not between", value1, value2, "aliUrl");
      return this;
    }

    public Criteria andAliPriceIsNull() {
      addCriterion("ALI_PRICE is null");
      return this;
    }

    public Criteria andAliPriceIsNotNull() {
      addCriterion("ALI_PRICE is not null");
      return this;
    }

    public Criteria andAliPriceEqualTo(BigDecimal value) {
      addCriterion("ALI_PRICE =", value, "aliPrice");
      return this;
    }

    public Criteria andAliPriceNotEqualTo(BigDecimal value) {
      addCriterion("ALI_PRICE <>", value, "aliPrice");
      return this;
    }

    public Criteria andAliPriceGreaterThan(BigDecimal value) {
      addCriterion("ALI_PRICE >", value, "aliPrice");
      return this;
    }

    public Criteria andAliPriceGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("ALI_PRICE >=", value, "aliPrice");
      return this;
    }

    public Criteria andAliPriceLessThan(BigDecimal value) {
      addCriterion("ALI_PRICE <", value, "aliPrice");
      return this;
    }

    public Criteria andAliPriceLessThanOrEqualTo(BigDecimal value) {
      addCriterion("ALI_PRICE <=", value, "aliPrice");
      return this;
    }

    public Criteria andAliPriceIn(List values) {
      addCriterion("ALI_PRICE in", values, "aliPrice");
      return this;
    }

    public Criteria andAliPriceNotIn(List values) {
      addCriterion("ALI_PRICE not in", values, "aliPrice");
      return this;
    }

    public Criteria andAliPriceBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("ALI_PRICE between", value1, value2, "aliPrice");
      return this;
    }

    public Criteria andAliPriceNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("ALI_PRICE not between", value1, value2, "aliPrice");
      return this;
    }

    public Criteria andAliRemarkIsNull() {
      addCriterion("ALI_REMARK is null");
      return this;
    }

    public Criteria andAliRemarkIsNotNull() {
      addCriterion("ALI_REMARK is not null");
      return this;
    }

    public Criteria andAliRemarkEqualTo(String value) {
      addCriterion("ALI_REMARK =", value, "aliRemark");
      return this;
    }

    public Criteria andAliRemarkNotEqualTo(String value) {
      addCriterion("ALI_REMARK <>", value, "aliRemark");
      return this;
    }

    public Criteria andAliRemarkGreaterThan(String value) {
      addCriterion("ALI_REMARK >", value, "aliRemark");
      return this;
    }

    public Criteria andAliRemarkGreaterThanOrEqualTo(String value) {
      addCriterion("ALI_REMARK >=", value, "aliRemark");
      return this;
    }

    public Criteria andAliRemarkLessThan(String value) {
      addCriterion("ALI_REMARK <", value, "aliRemark");
      return this;
    }

    public Criteria andAliRemarkLessThanOrEqualTo(String value) {
      addCriterion("ALI_REMARK <=", value, "aliRemark");
      return this;
    }

    public Criteria andAliRemarkLike(String value) {
      addCriterion("ALI_REMARK like", value, "aliRemark");
      return this;
    }

    public Criteria andAliRemarkNotLike(String value) {
      addCriterion("ALI_REMARK not like", value, "aliRemark");
      return this;
    }

    public Criteria andAliRemarkIn(List values) {
      addCriterion("ALI_REMARK in", values, "aliRemark");
      return this;
    }

    public Criteria andAliRemarkNotIn(List values) {
      addCriterion("ALI_REMARK not in", values, "aliRemark");
      return this;
    }

    public Criteria andAliRemarkBetween(String value1, String value2) {
      addCriterion("ALI_REMARK between", value1, value2, "aliRemark");
      return this;
    }

    public Criteria andAliRemarkNotBetween(String value1, String value2) {
      addCriterion("ALI_REMARK not between", value1, value2, "aliRemark");
      return this;
    }

    public Criteria andEbSiteIsNull() {
      addCriterion("EB_SITE is null");
      return this;
    }

    public Criteria andEbSiteIsNotNull() {
      addCriterion("EB_SITE is not null");
      return this;
    }

    public Criteria andEbSiteEqualTo(String value) {
      addCriterion("EB_SITE =", value, "ebSite");
      return this;
    }

    public Criteria andEbSiteNotEqualTo(String value) {
      addCriterion("EB_SITE <>", value, "ebSite");
      return this;
    }

    public Criteria andEbSiteGreaterThan(String value) {
      addCriterion("EB_SITE >", value, "ebSite");
      return this;
    }

    public Criteria andEbSiteGreaterThanOrEqualTo(String value) {
      addCriterion("EB_SITE >=", value, "ebSite");
      return this;
    }

    public Criteria andEbSiteLessThan(String value) {
      addCriterion("EB_SITE <", value, "ebSite");
      return this;
    }

    public Criteria andEbSiteLessThanOrEqualTo(String value) {
      addCriterion("EB_SITE <=", value, "ebSite");
      return this;
    }

    public Criteria andEbSiteLike(String value) {
      addCriterion("EB_SITE like", value, "ebSite");
      return this;
    }

    public Criteria andEbSiteNotLike(String value) {
      addCriterion("EB_SITE not like", value, "ebSite");
      return this;
    }

    public Criteria andEbSiteIn(List values) {
      addCriterion("EB_SITE in", values, "ebSite");
      return this;
    }

    public Criteria andEbSiteNotIn(List values) {
      addCriterion("EB_SITE not in", values, "ebSite");
      return this;
    }

    public Criteria andEbSiteBetween(String value1, String value2) {
      addCriterion("EB_SITE between", value1, value2, "ebSite");
      return this;
    }

    public Criteria andEbSiteNotBetween(String value1, String value2) {
      addCriterion("EB_SITE not between", value1, value2, "ebSite");
      return this;
    }

    public Criteria andItemIdIsNull() {
      addCriterion("ITEM_ID is null");
      return this;
    }

    public Criteria andItemIdIsNotNull() {
      addCriterion("ITEM_ID is not null");
      return this;
    }

    public Criteria andItemIdEqualTo(String value) {
      addCriterion("ITEM_ID =", value, "itemId");
      return this;
    }

    public Criteria andItemIdNotEqualTo(String value) {
      addCriterion("ITEM_ID <>", value, "itemId");
      return this;
    }

    public Criteria andItemIdGreaterThan(String value) {
      addCriterion("ITEM_ID >", value, "itemId");
      return this;
    }

    public Criteria andItemIdGreaterThanOrEqualTo(String value) {
      addCriterion("ITEM_ID >=", value, "itemId");
      return this;
    }

    public Criteria andItemIdLessThan(String value) {
      addCriterion("ITEM_ID <", value, "itemId");
      return this;
    }

    public Criteria andItemIdLessThanOrEqualTo(String value) {
      addCriterion("ITEM_ID <=", value, "itemId");
      return this;
    }

    public Criteria andItemIdLike(String value) {
      addCriterion("ITEM_ID like", value, "itemId");
      return this;
    }

    public Criteria andItemIdNotLike(String value) {
      addCriterion("ITEM_ID not like", value, "itemId");
      return this;
    }

    public Criteria andItemIdIn(List values) {
      addCriterion("ITEM_ID in", values, "itemId");
      return this;
    }

    public Criteria andItemIdNotIn(List values) {
      addCriterion("ITEM_ID not in", values, "itemId");
      return this;
    }

    public Criteria andItemIdBetween(String value1, String value2) {
      addCriterion("ITEM_ID between", value1, value2, "itemId");
      return this;
    }

    public Criteria andItemIdNotBetween(String value1, String value2) {
      addCriterion("ITEM_ID not between", value1, value2, "itemId");
      return this;
    }

    public Criteria andStartTimeIsNull() {
      addCriterion("START_TIME is null");
      return this;
    }

    public Criteria andStartTimeIsNotNull() {
      addCriterion("START_TIME is not null");
      return this;
    }

    public Criteria andStartTimeEqualTo(Date value) {
      addCriterion("START_TIME =", value, "startTime");
      return this;
    }

    public Criteria andStartTimeNotEqualTo(Date value) {
      addCriterion("START_TIME <>", value, "startTime");
      return this;
    }

    public Criteria andStartTimeGreaterThan(Date value) {
      addCriterion("START_TIME >", value, "startTime");
      return this;
    }

    public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("START_TIME >=", value, "startTime");
      return this;
    }

    public Criteria andStartTimeLessThan(Date value) {
      addCriterion("START_TIME <", value, "startTime");
      return this;
    }

    public Criteria andStartTimeLessThanOrEqualTo(Date value) {
      addCriterion("START_TIME <=", value, "startTime");
      return this;
    }

    public Criteria andStartTimeIn(List values) {
      addCriterion("START_TIME in", values, "startTime");
      return this;
    }

    public Criteria andStartTimeNotIn(List values) {
      addCriterion("START_TIME not in", values, "startTime");
      return this;
    }

    public Criteria andStartTimeBetween(Date value1, Date value2) {
      addCriterion("START_TIME between", value1, value2, "startTime");
      return this;
    }

    public Criteria andStartTimeNotBetween(Date value1, Date value2) {
      addCriterion("START_TIME not between", value1, value2, "startTime");
      return this;
    }

    public Criteria andEndTimeIsNull() {
      addCriterion("END_TIME is null");
      return this;
    }

    public Criteria andEndTimeIsNotNull() {
      addCriterion("END_TIME is not null");
      return this;
    }

    public Criteria andEndTimeEqualTo(Date value) {
      addCriterion("END_TIME =", value, "endTime");
      return this;
    }

    public Criteria andEndTimeNotEqualTo(Date value) {
      addCriterion("END_TIME <>", value, "endTime");
      return this;
    }

    public Criteria andEndTimeGreaterThan(Date value) {
      addCriterion("END_TIME >", value, "endTime");
      return this;
    }

    public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("END_TIME >=", value, "endTime");
      return this;
    }

    public Criteria andEndTimeLessThan(Date value) {
      addCriterion("END_TIME <", value, "endTime");
      return this;
    }

    public Criteria andEndTimeLessThanOrEqualTo(Date value) {
      addCriterion("END_TIME <=", value, "endTime");
      return this;
    }

    public Criteria andEndTimeIn(List values) {
      addCriterion("END_TIME in", values, "endTime");
      return this;
    }

    public Criteria andEndTimeNotIn(List values) {
      addCriterion("END_TIME not in", values, "endTime");
      return this;
    }

    public Criteria andEndTimeBetween(Date value1, Date value2) {
      addCriterion("END_TIME between", value1, value2, "endTime");
      return this;
    }

    public Criteria andEndTimeNotBetween(Date value1, Date value2) {
      addCriterion("END_TIME not between", value1, value2, "endTime");
      return this;
    }

    public Criteria andIsSellingIsNull() {
      addCriterion("IS_SELLING is null");
      return this;
    }

    public Criteria andIsSellingIsNotNull() {
      addCriterion("IS_SELLING is not null");
      return this;
    }

    public Criteria andIsSellingEqualTo(String value) {
      addCriterion("IS_SELLING =", value, "isSelling");
      return this;
    }

    public Criteria andIsSellingNotEqualTo(String value) {
      addCriterion("IS_SELLING <>", value, "isSelling");
      return this;
    }

    public Criteria andIsSellingGreaterThan(String value) {
      addCriterion("IS_SELLING >", value, "isSelling");
      return this;
    }

    public Criteria andIsSellingGreaterThanOrEqualTo(String value) {
      addCriterion("IS_SELLING >=", value, "isSelling");
      return this;
    }

    public Criteria andIsSellingLessThan(String value) {
      addCriterion("IS_SELLING <", value, "isSelling");
      return this;
    }

    public Criteria andIsSellingLessThanOrEqualTo(String value) {
      addCriterion("IS_SELLING <=", value, "isSelling");
      return this;
    }

    public Criteria andIsSellingLike(String value) {
      addCriterion("IS_SELLING like", value, "isSelling");
      return this;
    }

    public Criteria andIsSellingNotLike(String value) {
      addCriterion("IS_SELLING not like", value, "isSelling");
      return this;
    }

    public Criteria andIsSellingIn(List values) {
      addCriterion("IS_SELLING in", values, "isSelling");
      return this;
    }

    public Criteria andIsSellingNotIn(List values) {
      addCriterion("IS_SELLING not in", values, "isSelling");
      return this;
    }

    public Criteria andIsSellingBetween(String value1, String value2) {
      addCriterion("IS_SELLING between", value1, value2, "isSelling");
      return this;
    }

    public Criteria andIsSellingNotBetween(String value1, String value2) {
      addCriterion("IS_SELLING not between", value1, value2, "isSelling");
      return this;
    }

    public Criteria andSellingPerDayIsNull() {
      addCriterion("SELLING_PER_DAY is null");
      return this;
    }

    public Criteria andSellingPerDayIsNotNull() {
      addCriterion("SELLING_PER_DAY is not null");
      return this;
    }

    public Criteria andSellingPerDayEqualTo(BigDecimal value) {
      addCriterion("SELLING_PER_DAY =", value, "sellingPerDay");
      return this;
    }

    public Criteria andSellingPerDayNotEqualTo(BigDecimal value) {
      addCriterion("SELLING_PER_DAY <>", value, "sellingPerDay");
      return this;
    }

    public Criteria andSellingPerDayGreaterThan(BigDecimal value) {
      addCriterion("SELLING_PER_DAY >", value, "sellingPerDay");
      return this;
    }

    public Criteria andSellingPerDayGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("SELLING_PER_DAY >=", value, "sellingPerDay");
      return this;
    }

    public Criteria andSellingPerDayLessThan(BigDecimal value) {
      addCriterion("SELLING_PER_DAY <", value, "sellingPerDay");
      return this;
    }

    public Criteria andSellingPerDayLessThanOrEqualTo(BigDecimal value) {
      addCriterion("SELLING_PER_DAY <=", value, "sellingPerDay");
      return this;
    }

    public Criteria andSellingPerDayIn(List values) {
      addCriterion("SELLING_PER_DAY in", values, "sellingPerDay");
      return this;
    }

    public Criteria andSellingPerDayNotIn(List values) {
      addCriterion("SELLING_PER_DAY not in", values, "sellingPerDay");
      return this;
    }

    public Criteria andSellingPerDayBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("SELLING_PER_DAY between", value1, value2, "sellingPerDay");
      return this;
    }

    public Criteria andSellingPerDayNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("SELLING_PER_DAY not between", value1, value2, "sellingPerDay");
      return this;
    }

    public Criteria andSellingDaysIsNull() {
      addCriterion("SELLING_DAYS is null");
      return this;
    }

    public Criteria andSellingDaysIsNotNull() {
      addCriterion("SELLING_DAYS is not null");
      return this;
    }

    public Criteria andSellingDaysEqualTo(Long value) {
      addCriterion("SELLING_DAYS =", value, "sellingDays");
      return this;
    }

    public Criteria andSellingDaysNotEqualTo(Long value) {
      addCriterion("SELLING_DAYS <>", value, "sellingDays");
      return this;
    }

    public Criteria andSellingDaysGreaterThan(Long value) {
      addCriterion("SELLING_DAYS >", value, "sellingDays");
      return this;
    }

    public Criteria andSellingDaysGreaterThanOrEqualTo(Long value) {
      addCriterion("SELLING_DAYS >=", value, "sellingDays");
      return this;
    }

    public Criteria andSellingDaysLessThan(Long value) {
      addCriterion("SELLING_DAYS <", value, "sellingDays");
      return this;
    }

    public Criteria andSellingDaysLessThanOrEqualTo(Long value) {
      addCriterion("SELLING_DAYS <=", value, "sellingDays");
      return this;
    }

    public Criteria andSellingDaysIn(List values) {
      addCriterion("SELLING_DAYS in", values, "sellingDays");
      return this;
    }

    public Criteria andSellingDaysNotIn(List values) {
      addCriterion("SELLING_DAYS not in", values, "sellingDays");
      return this;
    }

    public Criteria andSellingDaysBetween(Long value1, Long value2) {
      addCriterion("SELLING_DAYS between", value1, value2, "sellingDays");
      return this;
    }

    public Criteria andSellingDaysNotBetween(Long value1, Long value2) {
      addCriterion("SELLING_DAYS not between", value1, value2, "sellingDays");
      return this;
    }

    public Criteria andCostIsNull() {
      addCriterion("COST is null");
      return this;
    }

    public Criteria andCostIsNotNull() {
      addCriterion("COST is not null");
      return this;
    }

    public Criteria andCostEqualTo(BigDecimal value) {
      addCriterion("COST =", value, "cost");
      return this;
    }

    public Criteria andCostNotEqualTo(BigDecimal value) {
      addCriterion("COST <>", value, "cost");
      return this;
    }

    public Criteria andCostGreaterThan(BigDecimal value) {
      addCriterion("COST >", value, "cost");
      return this;
    }

    public Criteria andCostGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("COST >=", value, "cost");
      return this;
    }

    public Criteria andCostLessThan(BigDecimal value) {
      addCriterion("COST <", value, "cost");
      return this;
    }

    public Criteria andCostLessThanOrEqualTo(BigDecimal value) {
      addCriterion("COST <=", value, "cost");
      return this;
    }

    public Criteria andCostIn(List values) {
      addCriterion("COST in", values, "cost");
      return this;
    }

    public Criteria andCostNotIn(List values) {
      addCriterion("COST not in", values, "cost");
      return this;
    }

    public Criteria andCostBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COST between", value1, value2, "cost");
      return this;
    }

    public Criteria andCostNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COST not between", value1, value2, "cost");
      return this;
    }

    public Criteria andProfitIsNull() {
      addCriterion("PROFIT is null");
      return this;
    }

    public Criteria andProfitIsNotNull() {
      addCriterion("PROFIT is not null");
      return this;
    }

    public Criteria andProfitEqualTo(BigDecimal value) {
      addCriterion("PROFIT =", value, "profit");
      return this;
    }

    public Criteria andProfitNotEqualTo(BigDecimal value) {
      addCriterion("PROFIT <>", value, "profit");
      return this;
    }

    public Criteria andProfitGreaterThan(BigDecimal value) {
      addCriterion("PROFIT >", value, "profit");
      return this;
    }

    public Criteria andProfitGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PROFIT >=", value, "profit");
      return this;
    }

    public Criteria andProfitLessThan(BigDecimal value) {
      addCriterion("PROFIT <", value, "profit");
      return this;
    }

    public Criteria andProfitLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PROFIT <=", value, "profit");
      return this;
    }

    public Criteria andProfitIn(List values) {
      addCriterion("PROFIT in", values, "profit");
      return this;
    }

    public Criteria andProfitNotIn(List values) {
      addCriterion("PROFIT not in", values, "profit");
      return this;
    }

    public Criteria andProfitBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PROFIT between", value1, value2, "profit");
      return this;
    }

    public Criteria andProfitNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PROFIT not between", value1, value2, "profit");
      return this;
    }

    public Criteria andProfitRateIsNull() {
      addCriterion("PROFIT_RATE is null");
      return this;
    }

    public Criteria andProfitRateIsNotNull() {
      addCriterion("PROFIT_RATE is not null");
      return this;
    }

    public Criteria andProfitRateEqualTo(BigDecimal value) {
      addCriterion("PROFIT_RATE =", value, "profitRate");
      return this;
    }

    public Criteria andProfitRateNotEqualTo(BigDecimal value) {
      addCriterion("PROFIT_RATE <>", value, "profitRate");
      return this;
    }

    public Criteria andProfitRateGreaterThan(BigDecimal value) {
      addCriterion("PROFIT_RATE >", value, "profitRate");
      return this;
    }

    public Criteria andProfitRateGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PROFIT_RATE >=", value, "profitRate");
      return this;
    }

    public Criteria andProfitRateLessThan(BigDecimal value) {
      addCriterion("PROFIT_RATE <", value, "profitRate");
      return this;
    }

    public Criteria andProfitRateLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PROFIT_RATE <=", value, "profitRate");
      return this;
    }

    public Criteria andProfitRateIn(List values) {
      addCriterion("PROFIT_RATE in", values, "profitRate");
      return this;
    }

    public Criteria andProfitRateNotIn(List values) {
      addCriterion("PROFIT_RATE not in", values, "profitRate");
      return this;
    }

    public Criteria andProfitRateBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PROFIT_RATE between", value1, value2, "profitRate");
      return this;
    }

    public Criteria andProfitRateNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PROFIT_RATE not between", value1, value2, "profitRate");
      return this;
    }

    public Criteria andEbImageUrlIsNull() {
      addCriterion("EB_IMAGE_URL is null");
      return this;
    }

    public Criteria andEbImageUrlIsNotNull() {
      addCriterion("EB_IMAGE_URL is not null");
      return this;
    }

    public Criteria andEbImageUrlEqualTo(String value) {
      addCriterion("EB_IMAGE_URL =", value, "ebImageUrl");
      return this;
    }

    public Criteria andEbImageUrlNotEqualTo(String value) {
      addCriterion("EB_IMAGE_URL <>", value, "ebImageUrl");
      return this;
    }

    public Criteria andEbImageUrlGreaterThan(String value) {
      addCriterion("EB_IMAGE_URL >", value, "ebImageUrl");
      return this;
    }

    public Criteria andEbImageUrlGreaterThanOrEqualTo(String value) {
      addCriterion("EB_IMAGE_URL >=", value, "ebImageUrl");
      return this;
    }

    public Criteria andEbImageUrlLessThan(String value) {
      addCriterion("EB_IMAGE_URL <", value, "ebImageUrl");
      return this;
    }

    public Criteria andEbImageUrlLessThanOrEqualTo(String value) {
      addCriterion("EB_IMAGE_URL <=", value, "ebImageUrl");
      return this;
    }

    public Criteria andEbImageUrlLike(String value) {
      addCriterion("EB_IMAGE_URL like", value, "ebImageUrl");
      return this;
    }

    public Criteria andEbImageUrlNotLike(String value) {
      addCriterion("EB_IMAGE_URL not like", value, "ebImageUrl");
      return this;
    }

    public Criteria andEbImageUrlIn(List values) {
      addCriterion("EB_IMAGE_URL in", values, "ebImageUrl");
      return this;
    }

    public Criteria andEbImageUrlNotIn(List values) {
      addCriterion("EB_IMAGE_URL not in", values, "ebImageUrl");
      return this;
    }

    public Criteria andEbImageUrlBetween(String value1, String value2) {
      addCriterion("EB_IMAGE_URL between", value1, value2, "ebImageUrl");
      return this;
    }

    public Criteria andEbImageUrlNotBetween(String value1, String value2) {
      addCriterion("EB_IMAGE_URL not between", value1, value2, "ebImageUrl");
      return this;
    }

    public Criteria andTransportModeIsNull() {
      addCriterion("TRANSPORT_MODE is null");
      return this;
    }

    public Criteria andTransportModeIsNotNull() {
      addCriterion("TRANSPORT_MODE is not null");
      return this;
    }

    public Criteria andTransportModeEqualTo(String value) {
      addCriterion("TRANSPORT_MODE =", value, "transportMode");
      return this;
    }

    public Criteria andTransportModeNotEqualTo(String value) {
      addCriterion("TRANSPORT_MODE <>", value, "transportMode");
      return this;
    }

    public Criteria andTransportModeGreaterThan(String value) {
      addCriterion("TRANSPORT_MODE >", value, "transportMode");
      return this;
    }

    public Criteria andTransportModeGreaterThanOrEqualTo(String value) {
      addCriterion("TRANSPORT_MODE >=", value, "transportMode");
      return this;
    }

    public Criteria andTransportModeLessThan(String value) {
      addCriterion("TRANSPORT_MODE <", value, "transportMode");
      return this;
    }

    public Criteria andTransportModeLessThanOrEqualTo(String value) {
      addCriterion("TRANSPORT_MODE <=", value, "transportMode");
      return this;
    }

    public Criteria andTransportModeLike(String value) {
      addCriterion("TRANSPORT_MODE like", value, "transportMode");
      return this;
    }

    public Criteria andTransportModeNotLike(String value) {
      addCriterion("TRANSPORT_MODE not like", value, "transportMode");
      return this;
    }

    public Criteria andTransportModeIn(List values) {
      addCriterion("TRANSPORT_MODE in", values, "transportMode");
      return this;
    }

    public Criteria andTransportModeNotIn(List values) {
      addCriterion("TRANSPORT_MODE not in", values, "transportMode");
      return this;
    }

    public Criteria andTransportModeBetween(String value1, String value2) {
      addCriterion("TRANSPORT_MODE between", value1, value2, "transportMode");
      return this;
    }

    public Criteria andTransportModeNotBetween(String value1, String value2) {
      addCriterion("TRANSPORT_MODE not between", value1, value2, "transportMode");
      return this;
    }
  }
}