package com.ufgov.gk.common.ebay.model;

public class EbItemChecked {

  public static String CHECKED = "4";

  public static String WAITING_CHECK = "-1";

  public static String ALL = "all";

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM_CHECKED.ITEM_ID
   *
   * @abatorgenerated Fri Sep 21 17:00:47 CST 2012
   */
  private String itemId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM_CHECKED.SELLER_ID
   *
   * @abatorgenerated Fri Sep 21 17:00:47 CST 2012
   */
  private String sellerId;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM_CHECKED.ITEM_ID
   *
   * @return the value of EB_ITEM_CHECKED.ITEM_ID
   *
   * @abatorgenerated Fri Sep 21 17:00:47 CST 2012
   */
  public String getItemId() {
    return itemId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM_CHECKED.ITEM_ID
   *
   * @param itemId the value for EB_ITEM_CHECKED.ITEM_ID
   *
   * @abatorgenerated Fri Sep 21 17:00:47 CST 2012
   */
  public void setItemId(String itemId) {
    this.itemId = itemId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM_CHECKED.SELLER_ID
   *
   * @return the value of EB_ITEM_CHECKED.SELLER_ID
   *
   * @abatorgenerated Fri Sep 21 17:00:47 CST 2012
   */
  public String getSellerId() {
    return sellerId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM_CHECKED.SELLER_ID
   *
   * @param sellerId the value for EB_ITEM_CHECKED.SELLER_ID
   *
   * @abatorgenerated Fri Sep 21 17:00:47 CST 2012
   */
  public void setSellerId(String sellerId) {
    this.sellerId = sellerId;
  }
}