package com.ufgov.gk.common.ebay.model;

import java.math.BigDecimal;
import java.util.Date;

import com.ufgov.gk.common.commonbiz.model.BaseBill;

public class EbItem extends BaseBill {

  //ºòÑ¡×´Ì¬ VS_EB_CANDIDATE_ITEM_STATUS
  private String candidateStatus;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.ITEM_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String itemId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.START_TIME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private Date startTime;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.END_TIME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private Date endTime;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.SOLD_QUALITY
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private Long soldQuality;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.PRICE
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private BigDecimal price;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.SHIPPING_TYPE
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String shippingType;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.SHIPPING_FEE
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private BigDecimal shippingFee;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.SELLING_PER_DAY
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private BigDecimal sellingPerDay;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.SELLING_DAYS
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private Long sellingDays;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.NAME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String name;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.URL
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String url;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.SELLER_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String sellerId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.IMAGE_URL
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String imageUrl;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.CURRENCY_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String currencyId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.SITE_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String siteId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.BID_COUNT
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private Integer bidCount;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.COUNTRY
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String country;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.CATEGORY_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String categoryId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.CATEGORY_NAME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String categoryName;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.LOCATION
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String location;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.TIME_LEFT
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String timeLeft;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.SKU
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String sku;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_ITEM.LISTING_TYPEL
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  private String listingType;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.ITEM_ID
   *
   * @return the value of EB_ITEM.ITEM_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getItemId() {
    return itemId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.ITEM_ID
   *
   * @param itemId the value for EB_ITEM.ITEM_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setItemId(String itemId) {
    this.itemId = itemId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.START_TIME
   *
   * @return the value of EB_ITEM.START_TIME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public Date getStartTime() {
    return startTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.START_TIME
   *
   * @param startTime the value for EB_ITEM.START_TIME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setStartTime(Date startTime) {
    this.startTime = startTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.END_TIME
   *
   * @return the value of EB_ITEM.END_TIME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public Date getEndTime() {
    return endTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.END_TIME
   *
   * @param endTime the value for EB_ITEM.END_TIME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setEndTime(Date endTime) {
    this.endTime = endTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.SOLD_QUALITY
   *
   * @return the value of EB_ITEM.SOLD_QUALITY
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public Long getSoldQuality() {
    return soldQuality;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.SOLD_QUALITY
   *
   * @param soldQuality the value for EB_ITEM.SOLD_QUALITY
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setSoldQuality(Long soldQuality) {
    this.soldQuality = soldQuality;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.PRICE
   *
   * @return the value of EB_ITEM.PRICE
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public BigDecimal getPrice() {
    return price;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.PRICE
   *
   * @param price the value for EB_ITEM.PRICE
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.SHIPPING_TYPE
   *
   * @return the value of EB_ITEM.SHIPPING_TYPE
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getShippingType() {
    return shippingType;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.SHIPPING_TYPE
   *
   * @param shippingType the value for EB_ITEM.SHIPPING_TYPE
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setShippingType(String shippingType) {
    this.shippingType = shippingType;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.SHIPPING_FEE
   *
   * @return the value of EB_ITEM.SHIPPING_FEE
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public BigDecimal getShippingFee() {
    return shippingFee;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.SHIPPING_FEE
   *
   * @param shippingFee the value for EB_ITEM.SHIPPING_FEE
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setShippingFee(BigDecimal shippingFee) {
    this.shippingFee = shippingFee;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.SELLING_PER_DAY
   *
   * @return the value of EB_ITEM.SELLING_PER_DAY
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public BigDecimal getSellingPerDay() {
    return sellingPerDay;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.SELLING_PER_DAY
   *
   * @param sellingPerDay the value for EB_ITEM.SELLING_PER_DAY
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setSellingPerDay(BigDecimal sellingPerDay) {
    this.sellingPerDay = sellingPerDay;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.SELLING_DAYS
   *
   * @return the value of EB_ITEM.SELLING_DAYS
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public Long getSellingDays() {
    return sellingDays;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.SELLING_DAYS
   *
   * @param sellingDays the value for EB_ITEM.SELLING_DAYS
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setSellingDays(Long sellingDays) {
    this.sellingDays = sellingDays;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.NAME
   *
   * @return the value of EB_ITEM.NAME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.NAME
   *
   * @param name the value for EB_ITEM.NAME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.URL
   *
   * @return the value of EB_ITEM.URL
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getUrl() {
    return url;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.URL
   *
   * @param url the value for EB_ITEM.URL
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.SELLER_ID
   *
   * @return the value of EB_ITEM.SELLER_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getSellerId() {
    return sellerId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.SELLER_ID
   *
   * @param sellerId the value for EB_ITEM.SELLER_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setSellerId(String sellerId) {
    this.sellerId = sellerId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.IMAGE_URL
   *
   * @return the value of EB_ITEM.IMAGE_URL
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getImageUrl() {
    return imageUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.IMAGE_URL
   *
   * @param imageUrl the value for EB_ITEM.IMAGE_URL
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.CURRENCY_ID
   *
   * @return the value of EB_ITEM.CURRENCY_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getCurrencyId() {
    return currencyId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.CURRENCY_ID
   *
   * @param currencyId the value for EB_ITEM.CURRENCY_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setCurrencyId(String currencyId) {
    this.currencyId = currencyId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.SITE_ID
   *
   * @return the value of EB_ITEM.SITE_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getSiteId() {
    return siteId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.SITE_ID
   *
   * @param siteId the value for EB_ITEM.SITE_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setSiteId(String siteId) {
    this.siteId = siteId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.BID_COUNT
   *
   * @return the value of EB_ITEM.BID_COUNT
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public Integer getBidCount() {
    return bidCount;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.BID_COUNT
   *
   * @param bidCount the value for EB_ITEM.BID_COUNT
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setBidCount(Integer bidCount) {
    this.bidCount = bidCount;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.COUNTRY
   *
   * @return the value of EB_ITEM.COUNTRY
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getCountry() {
    return country;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.COUNTRY
   *
   * @param country the value for EB_ITEM.COUNTRY
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.CATEGORY_ID
   *
   * @return the value of EB_ITEM.CATEGORY_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getCategoryId() {
    return categoryId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.CATEGORY_ID
   *
   * @param categoryId the value for EB_ITEM.CATEGORY_ID
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.CATEGORY_NAME
   *
   * @return the value of EB_ITEM.CATEGORY_NAME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getCategoryName() {
    return categoryName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.CATEGORY_NAME
   *
   * @param categoryName the value for EB_ITEM.CATEGORY_NAME
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.LOCATION
   *
   * @return the value of EB_ITEM.LOCATION
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getLocation() {
    return location;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.LOCATION
   *
   * @param location the value for EB_ITEM.LOCATION
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setLocation(String location) {
    this.location = location;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.TIME_LEFT
   *
   * @return the value of EB_ITEM.TIME_LEFT
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getTimeLeft() {
    return timeLeft;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.TIME_LEFT
   *
   * @param timeLeft the value for EB_ITEM.TIME_LEFT
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setTimeLeft(String timeLeft) {
    this.timeLeft = timeLeft;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.SKU
   *
   * @return the value of EB_ITEM.SKU
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getSku() {
    return sku;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.SKU
   *
   * @param sku the value for EB_ITEM.SKU
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setSku(String sku) {
    this.sku = sku;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_ITEM.LISTING_TYPEL
   *
   * @return the value of EB_ITEM.LISTING_TYPEL
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public String getListingType() {
    return listingType;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_ITEM.LISTING_TYPEL
   *
   * @param listingType the value for EB_ITEM.LISTING_TYPEL
   *
   * @abatorgenerated Sat Jul 07 20:05:01 CST 2012
   */
  public void setListingType(String listingType) {
    this.listingType = listingType;
  }

  public String getCandidateStatus() {
    return candidateStatus;
  }

  public void setCandidateStatus(String candidateStatus) {
    this.candidateStatus = candidateStatus;
  }
}