package com.ufgov.gk.common.ebay.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.ufgov.gk.common.commonbiz.model.BaseBill;

public class EbRetrievalTask extends BaseBill {

  public static String STATUS_NEW = "0";//新增

  public static String STATUS_RUNNING = "1";//运行

  public static String STATUS_EXCEPTION = "2";//异常

  public static String STATUS_STOP = "3";//停止

  public static String STATUS_COMPLETE = "4";//完成

  public static String STATUS_SUSPEND = "5";//暂停

  public static String STATUS_WAITING = "6";//等待

  public static String RETRIEVAL_TYPE_END_TIME = "2";//结束时间模式检索

  public static String RETRIEVAL_TYPE_START_TIME = "1";//开始时间模式检索

  public static String RETRIEVAL_TYPE_BOTH = "3";//两种都检索

  private List<EbItem> itemsLst = new ArrayList<EbItem>();

  private List<EbItemGroup> itemGroupLst = new ArrayList<EbItemGroup>();

  private String groupId;

  private Long feedback;

  private String attentionStatus;

  private String contry;

  private String imageSite;

  private EbSeller ebSeller;

  private Date analyseTime;

  private String analyseStatus;

  public static final String ANALYSE_STATUS_NO = "0"; //待分析

  public static final String ANALYSE_STATUS_ING = "1"; //分析中

  public static final String ANALYSE_STATUS_YES = "2"; //已分析

  public static final String ANALYSE_STATUS_UPDATE = "3"; //已更新

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.SELLER_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String sellerId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.TASK_START_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Date taskStartTime;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.RETRIEVAL_TYPE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String retrievalType;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.SELLING_ITEM_QUALITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Long sellingItemQuality;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.STATUS
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String status;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.TOTAL_ITEM_QUALITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Long totalItemQuality;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.RETRIEVAL_ANCHOR_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Date retrievalAnchorTime;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.STEP
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Long step;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.TIME_CONSUMING
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String timeConsuming;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.RETRIEVAL_MONTHS
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Long retrievalMonths;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.TOTAL_SOLD_AMOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private BigDecimal totalSoldAmount;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.TOTAL_SOLD_QUALITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Long totalSoldQuality;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_RETRIEVAL_TASK.CREATE_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Date createTime;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.SELLER_ID
   *
   * @return the value of EB_RETRIEVAL_TASK.SELLER_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getSellerId() {
    return sellerId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.SELLER_ID
   *
   * @param sellerId the value for EB_RETRIEVAL_TASK.SELLER_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setSellerId(String sellerId) {
    this.sellerId = sellerId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.TASK_START_TIME
   *
   * @return the value of EB_RETRIEVAL_TASK.TASK_START_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Date getTaskStartTime() {
    return taskStartTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.TASK_START_TIME
   *
   * @param taskStartTime the value for EB_RETRIEVAL_TASK.TASK_START_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setTaskStartTime(Date taskStartTime) {
    this.taskStartTime = taskStartTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.RETRIEVAL_TYPE
   *
   * @return the value of EB_RETRIEVAL_TASK.RETRIEVAL_TYPE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getRetrievalType() {
    return retrievalType;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.RETRIEVAL_TYPE
   *
   * @param retrievalType the value for EB_RETRIEVAL_TASK.RETRIEVAL_TYPE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setRetrievalType(String retrievalType) {
    this.retrievalType = retrievalType;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.SELLING_ITEM_QUALITY
   *
   * @return the value of EB_RETRIEVAL_TASK.SELLING_ITEM_QUALITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Long getSellingItemQuality() {
    return sellingItemQuality;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.SELLING_ITEM_QUALITY
   *
   * @param sellingItemQuality the value for EB_RETRIEVAL_TASK.SELLING_ITEM_QUALITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setSellingItemQuality(Long sellingItemQuality) {
    this.sellingItemQuality = sellingItemQuality;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.STATUS
   *
   * @return the value of EB_RETRIEVAL_TASK.STATUS
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getStatus() {
    return status;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.STATUS
   *
   * @param status the value for EB_RETRIEVAL_TASK.STATUS
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.TOTAL_ITEM_QUALITY
   *
   * @return the value of EB_RETRIEVAL_TASK.TOTAL_ITEM_QUALITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Long getTotalItemQuality() {
    return totalItemQuality;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.TOTAL_ITEM_QUALITY
   *
   * @param totalItemQuality the value for EB_RETRIEVAL_TASK.TOTAL_ITEM_QUALITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setTotalItemQuality(Long totalItemQuality) {
    this.totalItemQuality = totalItemQuality;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.RETRIEVAL_ANCHOR_TIME
   *
   * @return the value of EB_RETRIEVAL_TASK.RETRIEVAL_ANCHOR_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Date getRetrievalAnchorTime() {
    return retrievalAnchorTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.RETRIEVAL_ANCHOR_TIME
   *
   * @param retrievalAnchorTime the value for EB_RETRIEVAL_TASK.RETRIEVAL_ANCHOR_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setRetrievalAnchorTime(Date retrievalAnchorTime) {
    this.retrievalAnchorTime = retrievalAnchorTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.STEP
   *
   * @return the value of EB_RETRIEVAL_TASK.STEP
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Long getStep() {
    return step;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.STEP
   *
   * @param step the value for EB_RETRIEVAL_TASK.STEP
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setStep(Long step) {
    this.step = step;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.TIME_CONSUMING
   *
   * @return the value of EB_RETRIEVAL_TASK.TIME_CONSUMING
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getTimeConsuming() {
    return timeConsuming;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.TIME_CONSUMING
   *
   * @param timeConsuming the value for EB_RETRIEVAL_TASK.TIME_CONSUMING
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setTimeConsuming(String timeConsuming) {
    this.timeConsuming = timeConsuming;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.RETRIEVAL_MONTHS
   *
   * @return the value of EB_RETRIEVAL_TASK.RETRIEVAL_MONTHS
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Long getRetrievalMonths() {
    return retrievalMonths;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.RETRIEVAL_MONTHS
   *
   * @param retrievalMonths the value for EB_RETRIEVAL_TASK.RETRIEVAL_MONTHS
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setRetrievalMonths(Long retrievalMonths) {
    this.retrievalMonths = retrievalMonths;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.TOTAL_SOLD_AMOUNT
   *
   * @return the value of EB_RETRIEVAL_TASK.TOTAL_SOLD_AMOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public BigDecimal getTotalSoldAmount() {
    return totalSoldAmount;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.TOTAL_SOLD_AMOUNT
   *
   * @param totalSoldAmount the value for EB_RETRIEVAL_TASK.TOTAL_SOLD_AMOUNT
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setTotalSoldAmount(BigDecimal totalSoldAmount) {
    this.totalSoldAmount = totalSoldAmount;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.TOTAL_SOLD_QUALITY
   *
   * @return the value of EB_RETRIEVAL_TASK.TOTAL_SOLD_QUALITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Long getTotalSoldQuality() {
    return totalSoldQuality;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.TOTAL_SOLD_QUALITY
   *
   * @param totalSoldQuality the value for EB_RETRIEVAL_TASK.TOTAL_SOLD_QUALITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setTotalSoldQuality(Long totalSoldQuality) {
    this.totalSoldQuality = totalSoldQuality;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_RETRIEVAL_TASK.CREATE_TIME
   *
   * @return the value of EB_RETRIEVAL_TASK.CREATE_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_RETRIEVAL_TASK.CREATE_TIME
   *
   * @param createTime the value for EB_RETRIEVAL_TASK.CREATE_TIME
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  public List<EbItem> getItemsLst() {
    return itemsLst;
  }

  public void setItemsLst(List<EbItem> itemsLst) {
    this.itemsLst = itemsLst;
  }

  public List<EbItemGroup> getItemGroupLst() {
    return itemGroupLst;
  }

  public void setItemGroupLst(List<EbItemGroup> itemGroupLst) {
    this.itemGroupLst = itemGroupLst;
  }

  public String getGroupId() {
    if (this.ebSeller != null) {
      return this.ebSeller.getGroupId();
    }
    return groupId;
  }

  public void setGroupId(String groupId) {
    if (this.ebSeller != null) {
      this.ebSeller.setGroupId(groupId);
    }
    this.groupId = groupId;
  }

  public EbSeller getEbSeller() {
    return ebSeller;
  }

  public void setEbSeller(EbSeller ebSeller) {
    this.ebSeller = ebSeller;
  }

  public Date getAnalyseTime() {
    return analyseTime;
  }

  public void setAnalyseTime(Date analyseTime) {
    this.analyseTime = analyseTime;
  }

  public String getAnalyseStatus() {
    return analyseStatus;
  }

  public void setAnalyseStatus(String analyseStatus) {
    this.analyseStatus = analyseStatus;
  }

  public Long getFeedback() {
    if (this.ebSeller != null) {
      return this.ebSeller.getFeedback();
    }
    return feedback;
  }

  public void setFeedback(Long feedBack) {
    if (this.ebSeller != null) {
      this.ebSeller.setFeedback(feedBack);
    }
    this.feedback = feedBack;
  }

  public String getAttentionStatus() {
    if (this.ebSeller != null) {
      return this.ebSeller.getAttentionStatus();
    }
    return attentionStatus;
  }

  public void setAttentionStatus(String attentionStatus) {
    if (this.ebSeller != null) {
      this.ebSeller.setAttentionStatus(attentionStatus);
    }
    this.attentionStatus = attentionStatus;
  }

  public String getContry() {
    if (this.ebSeller != null) {
      return this.ebSeller.getContry();
    }
    return contry;
  }

  public void setContry(String contry) {
    if (this.ebSeller != null) {
      this.ebSeller.setContry(contry);
    }
    this.contry = contry;
  }

  public String getRemark() {
    if (this.ebSeller != null) {
      return this.ebSeller.getRemark();
    }
    return remark;
  }

  public void setRemark(String remark) {
    if (this.ebSeller != null) {
      this.ebSeller.setRemark(remark);
    }
    this.remark = remark;
  }

  public String getImageSite() {
    if (this.ebSeller != null) {
      return this.ebSeller.getImageSite();
    }
    return imageSite;
  }

  public void setImageSite(String imageSite) {
    if (this.ebSeller != null) {
      this.ebSeller.setImageSite(imageSite);
    }
    this.imageSite = imageSite;
  }

}