package com.ufgov.gk.common.ebay.model;

import java.util.Date;

import com.ufgov.gk.common.commonbiz.model.BaseBill;

public class EbSeller extends BaseBill {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_SELLER.SELLER_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String sellerId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_SELLER.CONTRY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String contry;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_SELLER.REGISTER_DATE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Date registerDate;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_SELLER.FEEDBACK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private Long feedback;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_SELLER.GROUP_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String groupId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_SELLER.CITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String city;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_SELLER.REMARK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String remark;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column EB_SELLER.IMAGE_SITE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private String imageSite;

  private String attentionStatus;

  private EbSellerGroup sellerGroup;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_SELLER.SELLER_ID
   *
   * @return the value of EB_SELLER.SELLER_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getSellerId() {
    return sellerId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_SELLER.SELLER_ID
   *
   * @param sellerId the value for EB_SELLER.SELLER_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setSellerId(String sellerId) {
    this.sellerId = sellerId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_SELLER.CONTRY
   *
   * @return the value of EB_SELLER.CONTRY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getContry() {
    return contry;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_SELLER.CONTRY
   *
   * @param contry the value for EB_SELLER.CONTRY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setContry(String contry) {
    this.contry = contry;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_SELLER.REGISTER_DATE
   *
   * @return the value of EB_SELLER.REGISTER_DATE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Date getRegisterDate() {
    return registerDate;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_SELLER.REGISTER_DATE
   *
   * @param registerDate the value for EB_SELLER.REGISTER_DATE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setRegisterDate(Date registerDate) {
    this.registerDate = registerDate;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_SELLER.FEEDBACK
   *
   * @return the value of EB_SELLER.FEEDBACK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Long getFeedback() {
    return feedback;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_SELLER.FEEDBACK
   *
   * @param feedback the value for EB_SELLER.FEEDBACK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setFeedback(Long feedback) {
    this.feedback = feedback;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_SELLER.GROUP_ID
   *
   * @return the value of EB_SELLER.GROUP_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getGroupId() {
    return groupId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_SELLER.GROUP_ID
   *
   * @param groupId the value for EB_SELLER.GROUP_ID
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_SELLER.CITY
   *
   * @return the value of EB_SELLER.CITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getCity() {
    return city;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_SELLER.CITY
   *
   * @param city the value for EB_SELLER.CITY
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setCity(String city) {
    this.city = city;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_SELLER.REMARK
   *
   * @return the value of EB_SELLER.REMARK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getRemark() {
    return remark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_SELLER.REMARK
   *
   * @param remark the value for EB_SELLER.REMARK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setRemark(String remark) {
    this.remark = remark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column EB_SELLER.IMAGE_SITE
   *
   * @return the value of EB_SELLER.IMAGE_SITE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getImageSite() {
    return imageSite;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column EB_SELLER.IMAGE_SITE
   *
   * @param imageSite the value for EB_SELLER.IMAGE_SITE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setImageSite(String imageSite) {
    this.imageSite = imageSite;
  }

  public EbSellerGroup getSellerGroup() {
    return sellerGroup;
  }

  public void setSellerGroup(EbSellerGroup sellerGroup) {
    this.sellerGroup = sellerGroup;
  }

  public String getAttentionStatus() {
    return attentionStatus;
  }

  public void setAttentionStatus(String attentionStatus) {
    this.attentionStatus = attentionStatus;
  }
}