package com.ufgov.gk.common.ebay.model;

public class EbSellerSiteStoreKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EB_SELLER_SITE_STORE.SELLER_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    private String sellerId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EB_SELLER_SITE_STORE.SITE_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    private String siteId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EB_SELLER_SITE_STORE.SELLER_ID
     *
     * @return the value of EB_SELLER_SITE_STORE.SELLER_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EB_SELLER_SITE_STORE.SELLER_ID
     *
     * @param sellerId the value for EB_SELLER_SITE_STORE.SELLER_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EB_SELLER_SITE_STORE.SITE_ID
     *
     * @return the value of EB_SELLER_SITE_STORE.SITE_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EB_SELLER_SITE_STORE.SITE_ID
     *
     * @param siteId the value for EB_SELLER_SITE_STORE.SITE_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }
}