package com.ufgov.gk.common.ebay.model;

public class EbSellerCategoryKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EB_SELLER_CATEGORY.CATEGORY_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    private String categoryId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EB_SELLER_CATEGORY.SELLER_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    private String sellerId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EB_SELLER_CATEGORY.CATEGORY_ID
     *
     * @return the value of EB_SELLER_CATEGORY.CATEGORY_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EB_SELLER_CATEGORY.CATEGORY_ID
     *
     * @param categoryId the value for EB_SELLER_CATEGORY.CATEGORY_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EB_SELLER_CATEGORY.SELLER_ID
     *
     * @return the value of EB_SELLER_CATEGORY.SELLER_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EB_SELLER_CATEGORY.SELLER_ID
     *
     * @param sellerId the value for EB_SELLER_CATEGORY.SELLER_ID
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }
}