package com.ufgov.gk.common.ebay.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ufgov.gk.common.commonbiz.model.BaseBill;

public class EbSellerSiteStoreExample extends BaseBill {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  protected String orderByClause;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  protected List oredCriteria;

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public EbSellerSiteStoreExample() {
    oredCriteria = new ArrayList();
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  protected EbSellerSiteStoreExample(EbSellerSiteStoreExample example) {
    this.orderByClause = example.orderByClause;
    this.oredCriteria = example.oredCriteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public List getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void clear() {
    oredCriteria.clear();
  }

  /**
   * This class was generated by Abator for iBATIS.
   * This class corresponds to the database table EB_SELLER_SITE_STORE
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public static class Criteria {
    protected List criteriaWithoutValue;

    protected List criteriaWithSingleValue;

    protected List criteriaWithListValue;

    protected List criteriaWithBetweenValue;

    protected Criteria() {
      super();
      criteriaWithoutValue = new ArrayList();
      criteriaWithSingleValue = new ArrayList();
      criteriaWithListValue = new ArrayList();
      criteriaWithBetweenValue = new ArrayList();
    }

    public boolean isValid() {
      return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0
        || criteriaWithBetweenValue.size() > 0;
    }

    public List getCriteriaWithoutValue() {
      return criteriaWithoutValue;
    }

    public List getCriteriaWithSingleValue() {
      return criteriaWithSingleValue;
    }

    public List getCriteriaWithListValue() {
      return criteriaWithListValue;
    }

    public List getCriteriaWithBetweenValue() {
      return criteriaWithBetweenValue;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteriaWithoutValue.add(condition);
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("value", value);
      criteriaWithSingleValue.add(map);
    }

    protected void addCriterion(String condition, List values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", values);
      criteriaWithListValue.add(map);
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      List list = new ArrayList();
      list.add(value1);
      list.add(value2);
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", list);
      criteriaWithBetweenValue.add(map);
    }

    public Criteria andSellerIdIsNull() {
      addCriterion("SELLER_ID is null");
      return this;
    }

    public Criteria andSellerIdIsNotNull() {
      addCriterion("SELLER_ID is not null");
      return this;
    }

    public Criteria andSellerIdEqualTo(String value) {
      addCriterion("SELLER_ID =", value, "sellerId");
      return this;
    }

    public Criteria andSellerIdNotEqualTo(String value) {
      addCriterion("SELLER_ID <>", value, "sellerId");
      return this;
    }

    public Criteria andSellerIdGreaterThan(String value) {
      addCriterion("SELLER_ID >", value, "sellerId");
      return this;
    }

    public Criteria andSellerIdGreaterThanOrEqualTo(String value) {
      addCriterion("SELLER_ID >=", value, "sellerId");
      return this;
    }

    public Criteria andSellerIdLessThan(String value) {
      addCriterion("SELLER_ID <", value, "sellerId");
      return this;
    }

    public Criteria andSellerIdLessThanOrEqualTo(String value) {
      addCriterion("SELLER_ID <=", value, "sellerId");
      return this;
    }

    public Criteria andSellerIdLike(String value) {
      addCriterion("SELLER_ID like", value, "sellerId");
      return this;
    }

    public Criteria andSellerIdNotLike(String value) {
      addCriterion("SELLER_ID not like", value, "sellerId");
      return this;
    }

    public Criteria andSellerIdIn(List values) {
      addCriterion("SELLER_ID in", values, "sellerId");
      return this;
    }

    public Criteria andSellerIdNotIn(List values) {
      addCriterion("SELLER_ID not in", values, "sellerId");
      return this;
    }

    public Criteria andSellerIdBetween(String value1, String value2) {
      addCriterion("SELLER_ID between", value1, value2, "sellerId");
      return this;
    }

    public Criteria andSellerIdNotBetween(String value1, String value2) {
      addCriterion("SELLER_ID not between", value1, value2, "sellerId");
      return this;
    }

    public Criteria andSiteIdIsNull() {
      addCriterion("SITE_ID is null");
      return this;
    }

    public Criteria andSiteIdIsNotNull() {
      addCriterion("SITE_ID is not null");
      return this;
    }

    public Criteria andSiteIdEqualTo(String value) {
      addCriterion("SITE_ID =", value, "siteId");
      return this;
    }

    public Criteria andSiteIdNotEqualTo(String value) {
      addCriterion("SITE_ID <>", value, "siteId");
      return this;
    }

    public Criteria andSiteIdGreaterThan(String value) {
      addCriterion("SITE_ID >", value, "siteId");
      return this;
    }

    public Criteria andSiteIdGreaterThanOrEqualTo(String value) {
      addCriterion("SITE_ID >=", value, "siteId");
      return this;
    }

    public Criteria andSiteIdLessThan(String value) {
      addCriterion("SITE_ID <", value, "siteId");
      return this;
    }

    public Criteria andSiteIdLessThanOrEqualTo(String value) {
      addCriterion("SITE_ID <=", value, "siteId");
      return this;
    }

    public Criteria andSiteIdLike(String value) {
      addCriterion("SITE_ID like", value, "siteId");
      return this;
    }

    public Criteria andSiteIdNotLike(String value) {
      addCriterion("SITE_ID not like", value, "siteId");
      return this;
    }

    public Criteria andSiteIdIn(List values) {
      addCriterion("SITE_ID in", values, "siteId");
      return this;
    }

    public Criteria andSiteIdNotIn(List values) {
      addCriterion("SITE_ID not in", values, "siteId");
      return this;
    }

    public Criteria andSiteIdBetween(String value1, String value2) {
      addCriterion("SITE_ID between", value1, value2, "siteId");
      return this;
    }

    public Criteria andSiteIdNotBetween(String value1, String value2) {
      addCriterion("SITE_ID not between", value1, value2, "siteId");
      return this;
    }

    public Criteria andStoreUrlIsNull() {
      addCriterion("STORE_URL is null");
      return this;
    }

    public Criteria andStoreUrlIsNotNull() {
      addCriterion("STORE_URL is not null");
      return this;
    }

    public Criteria andStoreUrlEqualTo(String value) {
      addCriterion("STORE_URL =", value, "storeUrl");
      return this;
    }

    public Criteria andStoreUrlNotEqualTo(String value) {
      addCriterion("STORE_URL <>", value, "storeUrl");
      return this;
    }

    public Criteria andStoreUrlGreaterThan(String value) {
      addCriterion("STORE_URL >", value, "storeUrl");
      return this;
    }

    public Criteria andStoreUrlGreaterThanOrEqualTo(String value) {
      addCriterion("STORE_URL >=", value, "storeUrl");
      return this;
    }

    public Criteria andStoreUrlLessThan(String value) {
      addCriterion("STORE_URL <", value, "storeUrl");
      return this;
    }

    public Criteria andStoreUrlLessThanOrEqualTo(String value) {
      addCriterion("STORE_URL <=", value, "storeUrl");
      return this;
    }

    public Criteria andStoreUrlLike(String value) {
      addCriterion("STORE_URL like", value, "storeUrl");
      return this;
    }

    public Criteria andStoreUrlNotLike(String value) {
      addCriterion("STORE_URL not like", value, "storeUrl");
      return this;
    }

    public Criteria andStoreUrlIn(List values) {
      addCriterion("STORE_URL in", values, "storeUrl");
      return this;
    }

    public Criteria andStoreUrlNotIn(List values) {
      addCriterion("STORE_URL not in", values, "storeUrl");
      return this;
    }

    public Criteria andStoreUrlBetween(String value1, String value2) {
      addCriterion("STORE_URL between", value1, value2, "storeUrl");
      return this;
    }

    public Criteria andStoreUrlNotBetween(String value1, String value2) {
      addCriterion("STORE_URL not between", value1, value2, "storeUrl");
      return this;
    }

    public Criteria andStoreNameIsNull() {
      addCriterion("STORE_NAME is null");
      return this;
    }

    public Criteria andStoreNameIsNotNull() {
      addCriterion("STORE_NAME is not null");
      return this;
    }

    public Criteria andStoreNameEqualTo(String value) {
      addCriterion("STORE_NAME =", value, "storeName");
      return this;
    }

    public Criteria andStoreNameNotEqualTo(String value) {
      addCriterion("STORE_NAME <>", value, "storeName");
      return this;
    }

    public Criteria andStoreNameGreaterThan(String value) {
      addCriterion("STORE_NAME >", value, "storeName");
      return this;
    }

    public Criteria andStoreNameGreaterThanOrEqualTo(String value) {
      addCriterion("STORE_NAME >=", value, "storeName");
      return this;
    }

    public Criteria andStoreNameLessThan(String value) {
      addCriterion("STORE_NAME <", value, "storeName");
      return this;
    }

    public Criteria andStoreNameLessThanOrEqualTo(String value) {
      addCriterion("STORE_NAME <=", value, "storeName");
      return this;
    }

    public Criteria andStoreNameLike(String value) {
      addCriterion("STORE_NAME like", value, "storeName");
      return this;
    }

    public Criteria andStoreNameNotLike(String value) {
      addCriterion("STORE_NAME not like", value, "storeName");
      return this;
    }

    public Criteria andStoreNameIn(List values) {
      addCriterion("STORE_NAME in", values, "storeName");
      return this;
    }

    public Criteria andStoreNameNotIn(List values) {
      addCriterion("STORE_NAME not in", values, "storeName");
      return this;
    }

    public Criteria andStoreNameBetween(String value1, String value2) {
      addCriterion("STORE_NAME between", value1, value2, "storeName");
      return this;
    }

    public Criteria andStoreNameNotBetween(String value1, String value2) {
      addCriterion("STORE_NAME not between", value1, value2, "storeName");
      return this;
    }
  }
}