package com.ufgov.gk.server.ebay.dao;

import com.ufgov.gk.common.ebay.model.EbAppAccount;
import com.ufgov.gk.common.ebay.model.EbAppAccountExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EbAppAccountDAOImpl extends SqlMapClientDaoSupport implements EbAppAccountDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbAppAccountDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public void insert(EbAppAccount record) {
        getSqlMapClientTemplate().insert("EB_APP_ACCOUNT.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKey(EbAppAccount record) {
        int rows = getSqlMapClientTemplate().update("EB_APP_ACCOUNT.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKeySelective(EbAppAccount record) {
        int rows = getSqlMapClientTemplate().update("EB_APP_ACCOUNT.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public List selectByExample(EbAppAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("EB_APP_ACCOUNT.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbAppAccount selectByPrimaryKey(String appAccount) {
        EbAppAccount key = new EbAppAccount();
        key.setAppAccount(appAccount);
        EbAppAccount record = (EbAppAccount) getSqlMapClientTemplate().queryForObject("EB_APP_ACCOUNT.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByExample(EbAppAccountExample example) {
        int rows = getSqlMapClientTemplate().delete("EB_APP_ACCOUNT.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByPrimaryKey(String appAccount) {
        EbAppAccount key = new EbAppAccount();
        key.setAppAccount(appAccount);
        int rows = getSqlMapClientTemplate().delete("EB_APP_ACCOUNT.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int countByExample(EbAppAccountExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EB_APP_ACCOUNT.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExampleSelective(EbAppAccount record, EbAppAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_APP_ACCOUNT.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExample(EbAppAccount record, EbAppAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_APP_ACCOUNT.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table EB_APP_ACCOUNT
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    private static class UpdateByExampleParms extends EbAppAccountExample {
        private Object record;

        public UpdateByExampleParms(Object record, EbAppAccountExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}