package com.ufgov.gk.server.ebay.dao;

import com.ufgov.gk.common.ebay.model.EbAppServer;
import com.ufgov.gk.common.ebay.model.EbAppServerExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EbAppServerDAOImpl extends SqlMapClientDaoSupport implements EbAppServerDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbAppServerDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public void insert(EbAppServer record) {
        getSqlMapClientTemplate().insert("EB_APP_SERVER.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKey(EbAppServer record) {
        int rows = getSqlMapClientTemplate().update("EB_APP_SERVER.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKeySelective(EbAppServer record) {
        int rows = getSqlMapClientTemplate().update("EB_APP_SERVER.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public List selectByExample(EbAppServerExample example) {
        List list = getSqlMapClientTemplate().queryForList("EB_APP_SERVER.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbAppServer selectByPrimaryKey(String siteId) {
        EbAppServer key = new EbAppServer();
        key.setSiteId(siteId);
        EbAppServer record = (EbAppServer) getSqlMapClientTemplate().queryForObject("EB_APP_SERVER.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByExample(EbAppServerExample example) {
        int rows = getSqlMapClientTemplate().delete("EB_APP_SERVER.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByPrimaryKey(String siteId) {
        EbAppServer key = new EbAppServer();
        key.setSiteId(siteId);
        int rows = getSqlMapClientTemplate().delete("EB_APP_SERVER.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int countByExample(EbAppServerExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EB_APP_SERVER.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExampleSelective(EbAppServer record, EbAppServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_APP_SERVER.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExample(EbAppServer record, EbAppServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_APP_SERVER.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table EB_APP_SERVER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    private static class UpdateByExampleParms extends EbAppServerExample {
        private Object record;

        public UpdateByExampleParms(Object record, EbAppServerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}