package com.ufgov.gk.server.ebay.dao;

import java.util.List;

import com.ufgov.gk.common.ebay.model.EbCandidateItem;
import com.ufgov.gk.common.ebay.model.EbCandidateItemExample;

public interface EbCandidateItemDAO {
  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  void insert(EbCandidateItem record);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  int updateByPrimaryKey(EbCandidateItem record);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  int updateByPrimaryKeySelective(EbCandidateItem record);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  List selectByExample(EbCandidateItemExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  EbCandidateItem selectByPrimaryKey(String candidateId);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  int deleteByExample(EbCandidateItemExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  int deleteByPrimaryKey(String candidateId);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  int countByExample(EbCandidateItemExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  int updateByExampleSelective(EbCandidateItem record, EbCandidateItemExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM
   *
   * @abatorgenerated Wed Jul 11 23:15:51 CST 2012
   */
  int updateByExample(EbCandidateItem record, EbCandidateItemExample example);

  EbCandidateItem getEbCandidateItemByRefItemId(String itemId);

  void deleteBySeller(String sellerId);
}