package com.ufgov.gk.server.ebay.dao;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.SqlMapClientCallback;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ibatis.sqlmap.client.SqlMapExecutor;
import com.ufgov.gk.common.ebay.model.EbCandidateItemRef;
import com.ufgov.gk.common.ebay.model.EbCandidateItemRef2;
import com.ufgov.gk.common.ebay.model.EbCandidateItemRefExample;
import com.ufgov.gk.common.ebay.model.EbCandidateItemRefExample2;

public class EbCandidateItemRefDAOImpl extends SqlMapClientDaoSupport implements EbCandidateItemRefDAO {

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  public EbCandidateItemRefDAOImpl() {
    super();
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  public void insert(EbCandidateItemRef record) {
    getSqlMapClientTemplate().insert("EB_CANDIDATE_ITEM_REF.insert", record);
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  public List selectByExample(EbCandidateItemRefExample example) {
    List list = getSqlMapClientTemplate().queryForList("EB_CANDIDATE_ITEM_REF.selectByExample", example);
    return list;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  public int deleteByExample(EbCandidateItemRefExample2 example) {
    int rows = getSqlMapClientTemplate().delete("EB_CANDIDATE_ITEM_REF.deleteByExample", example);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  public int countByExample(EbCandidateItemRefExample example) {
    Integer count = (Integer) getSqlMapClientTemplate().queryForObject("EB_CANDIDATE_ITEM_REF.countByExample", example);
    return count.intValue();
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  public int updateByExampleSelective(EbCandidateItemRef record, EbCandidateItemRefExample example) {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = getSqlMapClientTemplate().update("EB_CANDIDATE_ITEM_REF.updateByExampleSelective", parms);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  public int updateByExample(EbCandidateItemRef record, EbCandidateItemRefExample example) {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = getSqlMapClientTemplate().update("EB_CANDIDATE_ITEM_REF.updateByExample", parms);
    return rows;
  }

  /**
   * This class was generated by Abator for iBATIS.
   * This class corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  private static class UpdateByExampleParms extends EbCandidateItemRefExample {
    private Object record;

    public UpdateByExampleParms(Object record, EbCandidateItemRefExample example) {
      super(example);
      this.record = record;
    }

    public Object getRecord() {
      return record;
    }
  }

  @Override
  public List<EbCandidateItemRef2> selectByPK(String candidateId) {
    // TODO Auto-generated method stub
    List list = getSqlMapClientTemplate().queryForList("EB_CANDIDATE_ITEM_REF.selectByPK", candidateId);
    return list;
  }

  @Override
  public void saveRefs(final List<EbCandidateItemRef2> candidateItemRefLst) {
    // TODO Auto-generated method stub

    getSqlMapClientTemplate().execute(new SqlMapClientCallback() {
      public Object doInSqlMapClient(SqlMapExecutor executor) throws SQLException {
        executor.startBatch();
        for (EbCandidateItemRef2 refItem : candidateItemRefLst) {
          executor.insert("EB_CANDIDATE_ITEM_REF.insert", refItem);
        }
        return executor.executeBatch();
      }
    });
  }

  @Override
  public void deleteBySeller(String sellerId) {
    // TODO Auto-generated method stub
    getSqlMapClientTemplate().delete("EB_CANDIDATE_ITEM_REF.deleteBySeller", sellerId);
  }

  @Override
  public List<EbCandidateItemRef2> getEbCandidateItemRef2BySeller(String sellerId) {
    // TODO Auto-generated method stub
    return getSqlMapClientTemplate().queryForList("EB_CANDIDATE_ITEM_REF.selectBySellerId", sellerId);

  }
}