package com.ufgov.gk.server.ebay.dao;

import java.util.List;

import com.ufgov.gk.common.ebay.model.EbCandidateItemRef;
import com.ufgov.gk.common.ebay.model.EbCandidateItemRef2;
import com.ufgov.gk.common.ebay.model.EbCandidateItemRefExample;
import com.ufgov.gk.common.ebay.model.EbCandidateItemRefExample2;

public interface EbCandidateItemRefDAO {
  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  void insert(EbCandidateItemRef record);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  List selectByExample(EbCandidateItemRefExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  int deleteByExample(EbCandidateItemRefExample2 ex);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  int countByExample(EbCandidateItemRefExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  int updateByExampleSelective(EbCandidateItemRef record, EbCandidateItemRefExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_CANDIDATE_ITEM_REF
   *
   * @abatorgenerated Wed Jul 11 23:15:21 CST 2012
   */
  int updateByExample(EbCandidateItemRef record, EbCandidateItemRefExample example);

  List<EbCandidateItemRef2> selectByPK(String candidateId);

  void saveRefs(List<EbCandidateItemRef2> candidateItemRefLst);

  void deleteBySeller(String sellerId);

  List<EbCandidateItemRef2> getEbCandidateItemRef2BySeller(String sellerId);
}