package com.ufgov.gk.server.ebay.dao;

import com.ufgov.gk.common.ebay.model.EbCategory;
import com.ufgov.gk.common.ebay.model.EbCategoryExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EbCategoryDAOImpl extends SqlMapClientDaoSupport implements EbCategoryDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbCategoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public void insert(EbCategory record) {
        getSqlMapClientTemplate().insert("EB_CATEGORY.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKey(EbCategory record) {
        int rows = getSqlMapClientTemplate().update("EB_CATEGORY.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKeySelective(EbCategory record) {
        int rows = getSqlMapClientTemplate().update("EB_CATEGORY.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public List selectByExample(EbCategoryExample example) {
        List list = getSqlMapClientTemplate().queryForList("EB_CATEGORY.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbCategory selectByPrimaryKey(String categoryId) {
        EbCategory key = new EbCategory();
        key.setCategoryId(categoryId);
        EbCategory record = (EbCategory) getSqlMapClientTemplate().queryForObject("EB_CATEGORY.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByExample(EbCategoryExample example) {
        int rows = getSqlMapClientTemplate().delete("EB_CATEGORY.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByPrimaryKey(String categoryId) {
        EbCategory key = new EbCategory();
        key.setCategoryId(categoryId);
        int rows = getSqlMapClientTemplate().delete("EB_CATEGORY.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int countByExample(EbCategoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EB_CATEGORY.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExampleSelective(EbCategory record, EbCategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_CATEGORY.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExample(EbCategory record, EbCategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_CATEGORY.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table EB_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    private static class UpdateByExampleParms extends EbCategoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, EbCategoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}