package com.ufgov.gk.server.ebay.dao;

import com.ufgov.gk.common.ebay.model.EbCurrency;
import com.ufgov.gk.common.ebay.model.EbCurrencyExample;
import java.util.List;

public interface EbCurrencyDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CURRENCY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    void insert(EbCurrency record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CURRENCY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByPrimaryKey(EbCurrency record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CURRENCY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByPrimaryKeySelective(EbCurrency record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CURRENCY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    List selectByExample(EbCurrencyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CURRENCY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    EbCurrency selectByPrimaryKey(String currencyId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CURRENCY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int deleteByExample(EbCurrencyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CURRENCY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int deleteByPrimaryKey(String currencyId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CURRENCY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int countByExample(EbCurrencyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CURRENCY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByExampleSelective(EbCurrency record, EbCurrencyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_CURRENCY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByExample(EbCurrency record, EbCurrencyExample example);
}