package com.ufgov.gk.server.ebay.dao;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.SqlMapClientCallback;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ibatis.sqlmap.client.SqlMapExecutor;
import com.ufgov.gk.common.ebay.model.EbItem;
import com.ufgov.gk.common.ebay.model.EbItemExample;
import com.ufgov.gk.common.ebay.model.EbItemGroup;

public class EbItemDAOImpl extends SqlMapClientDaoSupport implements EbItemDAO {

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public EbItemDAOImpl() {
    super();
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void insert(EbItem record) {
    getSqlMapClientTemplate().insert("EB_ITEM.insert", record);
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int updateByPrimaryKey(EbItem record) {
    int rows = getSqlMapClientTemplate().update("EB_ITEM.updateByPrimaryKey", record);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int updateByPrimaryKeySelective(EbItem record) {
    int rows = getSqlMapClientTemplate().update("EB_ITEM.updateByPrimaryKeySelective", record);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public List selectByExample(EbItemExample example) {
    List list = getSqlMapClientTemplate().queryForList("EB_ITEM.selectByExample", example);
    return list;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public EbItem selectByPrimaryKey(String itemId) {
    EbItem key = new EbItem();
    key.setItemId(itemId);
    EbItem record = (EbItem) getSqlMapClientTemplate().queryForObject("EB_ITEM.selectByPrimaryKey", key);
    return record;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int deleteByExample(EbItemExample example) {
    int rows = getSqlMapClientTemplate().delete("EB_ITEM.deleteByExample", example);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int deleteByPrimaryKey(String itemId) {
    EbItem key = new EbItem();
    key.setItemId(itemId);
    int rows = getSqlMapClientTemplate().delete("EB_ITEM.deleteByPrimaryKey", key);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int countByExample(EbItemExample example) {
    Integer count = (Integer) getSqlMapClientTemplate().queryForObject("EB_ITEM.countByExample", example);
    return count.intValue();
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int updateByExampleSelective(EbItem record, EbItemExample example) {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = getSqlMapClientTemplate().update("EB_ITEM.updateByExampleSelective", parms);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int updateByExample(EbItem record, EbItemExample example) {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = getSqlMapClientTemplate().update("EB_ITEM.updateByExample", parms);
    return rows;
  }

  /**
   * This class was generated by Abator for iBATIS.
   * This class corresponds to the database table EB_ITEM
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private static class UpdateByExampleParms extends EbItemExample {
    private Object record;

    public UpdateByExampleParms(Object record, EbItemExample example) {
      super(example);
      this.record = record;
    }

    public Object getRecord() {
      return record;
    }
  }

  @Override
  public void saveEbItems(final List<EbItem> ebItemLst) {
    if (ebItemLst != null && ebItemLst.size() > 0) {
      String name = ebItemLst.get(0).getSellerId();
      System.out.println(name + ": " + ebItemLst.size());
    }
    getSqlMapClientTemplate().execute(new SqlMapClientCallback() {
      public Object doInSqlMapClient(SqlMapExecutor executor) throws SQLException {
        executor.startBatch();
        int i = 0;
        for (EbItem ebItem : ebItemLst) {
          executor.insert("EB_ITEM.insert", ebItem);
        }
        return executor.executeBatch();
      }
    });
  }

  @Override
  public List<EbItemGroup> getEbItemGroup(EbItemExample example) {
    // TODO Auto-generated method stub
    List list = getSqlMapClientTemplate().queryForList("EB_ITEM.selectItemGroupByExample", example);
    return list;
  }
}