package com.ufgov.gk.server.ebay.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ufgov.gk.common.ebay.model.EbRetrievalTask;
import com.ufgov.gk.common.ebay.model.EbRetrievalTaskExample;

public class EbRetrievalTaskDAOImpl extends SqlMapClientDaoSupport implements EbRetrievalTaskDAO {

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public EbRetrievalTaskDAOImpl() {
    super();
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public void insert(EbRetrievalTask record) {
    getSqlMapClientTemplate().insert("EB_RETRIEVAL_TASK.insert", record);
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int updateByPrimaryKey(EbRetrievalTask record) {
    int rows = getSqlMapClientTemplate().update("EB_RETRIEVAL_TASK.updateByPrimaryKey", record);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int updateByPrimaryKeySelective(EbRetrievalTask record) {
    int rows = getSqlMapClientTemplate().update("EB_RETRIEVAL_TASK.updateByPrimaryKeySelective", record);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public List selectByExample(EbRetrievalTaskExample example) {
    List list = getSqlMapClientTemplate().queryForList("EB_RETRIEVAL_TASK.selectByExample", example);
    return list;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public EbRetrievalTask selectByPrimaryKey(String sellerId) {
    EbRetrievalTask key = new EbRetrievalTask();
    key.setSellerId(sellerId);
    EbRetrievalTask record = (EbRetrievalTask) getSqlMapClientTemplate().queryForObject("EB_RETRIEVAL_TASK.selectByPrimaryKey", key);
    return record;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int deleteByExample(EbRetrievalTaskExample example) {
    int rows = getSqlMapClientTemplate().delete("EB_RETRIEVAL_TASK.deleteByExample", example);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int deleteByPrimaryKey(String sellerId) {
    EbRetrievalTask key = new EbRetrievalTask();
    key.setSellerId(sellerId);
    int rows = getSqlMapClientTemplate().delete("EB_RETRIEVAL_TASK.deleteByPrimaryKey", key);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int countByExample(EbRetrievalTaskExample example) {
    Integer count = (Integer) getSqlMapClientTemplate().queryForObject("EB_RETRIEVAL_TASK.countByExample", example);
    return count.intValue();
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int updateByExampleSelective(EbRetrievalTask record, EbRetrievalTaskExample example) {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = getSqlMapClientTemplate().update("EB_RETRIEVAL_TASK.updateByExampleSelective", parms);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  public int updateByExample(EbRetrievalTask record, EbRetrievalTaskExample example) {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = getSqlMapClientTemplate().update("EB_RETRIEVAL_TASK.updateByExample", parms);
    return rows;
  }

  /**
   * This class was generated by Abator for iBATIS.
   * This class corresponds to the database table EB_RETRIEVAL_TASK
   *
   * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
   */
  private static class UpdateByExampleParms extends EbRetrievalTaskExample {
    private Object record;

    public UpdateByExampleParms(Object record, EbRetrievalTaskExample example) {
      super(example);
      this.record = record;
    }

    public Object getRecord() {
      return record;
    }
  }
}