package com.ufgov.gk.server.ebay.dao;

import com.ufgov.gk.common.ebay.model.EbSellerSiteStore;
import com.ufgov.gk.common.ebay.model.EbSellerSiteStoreExample;
import com.ufgov.gk.common.ebay.model.EbSellerSiteStoreKey;
import java.util.List;

public interface EbSellerSiteStoreDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_SITE_STORE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    void insert(EbSellerSiteStore record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_SITE_STORE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByPrimaryKey(EbSellerSiteStore record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_SITE_STORE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByPrimaryKeySelective(EbSellerSiteStore record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_SITE_STORE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    List selectByExample(EbSellerSiteStoreExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_SITE_STORE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    EbSellerSiteStore selectByPrimaryKey(EbSellerSiteStoreKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_SITE_STORE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int deleteByExample(EbSellerSiteStoreExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_SITE_STORE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int deleteByPrimaryKey(EbSellerSiteStoreKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_SITE_STORE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int countByExample(EbSellerSiteStoreExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_SITE_STORE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByExampleSelective(EbSellerSiteStore record, EbSellerSiteStoreExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_SITE_STORE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByExample(EbSellerSiteStore record, EbSellerSiteStoreExample example);
}