package com.ufgov.gk.server.ebay.dao;

import com.ufgov.gk.common.ebay.model.EbSeller;
import com.ufgov.gk.common.ebay.model.EbSellerExample;
import java.util.List;

public interface EbSellerDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    void insert(EbSeller record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByPrimaryKey(EbSeller record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByPrimaryKeySelective(EbSeller record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    List selectByExample(EbSellerExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    EbSeller selectByPrimaryKey(String sellerId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int deleteByExample(EbSellerExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int deleteByPrimaryKey(String sellerId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int countByExample(EbSellerExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByExampleSelective(EbSeller record, EbSellerExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByExample(EbSeller record, EbSellerExample example);

	boolean changeSellerIdFN(String sellerId, String newSellerId);
}