package com.ufgov.gk.server.ebay.dao;

import com.ufgov.gk.common.ebay.model.EbSellerGroup;
import com.ufgov.gk.common.ebay.model.EbSellerGroupExample;
import java.util.List;

public interface EbSellerGroupDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    void insert(EbSellerGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByPrimaryKey(EbSellerGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByPrimaryKeySelective(EbSellerGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    List selectByExample(EbSellerGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    EbSellerGroup selectByPrimaryKey(String groupId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int deleteByExample(EbSellerGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int deleteByPrimaryKey(String groupId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int countByExample(EbSellerGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByExampleSelective(EbSellerGroup record, EbSellerGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByExample(EbSellerGroup record, EbSellerGroupExample example);
}