package com.ufgov.gk.server.ebay.dao;

import com.ufgov.gk.common.ebay.model.EbSellerGroup;
import com.ufgov.gk.common.ebay.model.EbSellerGroupExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EbSellerGroupDAOImpl extends SqlMapClientDaoSupport implements EbSellerGroupDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbSellerGroupDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public void insert(EbSellerGroup record) {
        getSqlMapClientTemplate().insert("EB_SELLER_GROUP.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKey(EbSellerGroup record) {
        int rows = getSqlMapClientTemplate().update("EB_SELLER_GROUP.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKeySelective(EbSellerGroup record) {
        int rows = getSqlMapClientTemplate().update("EB_SELLER_GROUP.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public List selectByExample(EbSellerGroupExample example) {
        List list = getSqlMapClientTemplate().queryForList("EB_SELLER_GROUP.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbSellerGroup selectByPrimaryKey(String groupId) {
        EbSellerGroup key = new EbSellerGroup();
        key.setGroupId(groupId);
        EbSellerGroup record = (EbSellerGroup) getSqlMapClientTemplate().queryForObject("EB_SELLER_GROUP.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByExample(EbSellerGroupExample example) {
        int rows = getSqlMapClientTemplate().delete("EB_SELLER_GROUP.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByPrimaryKey(String groupId) {
        EbSellerGroup key = new EbSellerGroup();
        key.setGroupId(groupId);
        int rows = getSqlMapClientTemplate().delete("EB_SELLER_GROUP.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int countByExample(EbSellerGroupExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EB_SELLER_GROUP.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExampleSelective(EbSellerGroup record, EbSellerGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_SELLER_GROUP.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExample(EbSellerGroup record, EbSellerGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_SELLER_GROUP.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table EB_SELLER_GROUP
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    private static class UpdateByExampleParms extends EbSellerGroupExample {
        private Object record;

        public UpdateByExampleParms(Object record, EbSellerGroupExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}