package com.ufgov.gk.server.ebay.dao;

import com.ufgov.gk.common.ebay.model.EbSellerCategory;
import com.ufgov.gk.common.ebay.model.EbSellerCategoryExample;
import com.ufgov.gk.common.ebay.model.EbSellerCategoryKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EbSellerCategoryDAOImpl extends SqlMapClientDaoSupport implements EbSellerCategoryDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbSellerCategoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public void insert(EbSellerCategory record) {
        getSqlMapClientTemplate().insert("EB_SELLER_CATEGORY.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKey(EbSellerCategory record) {
        int rows = getSqlMapClientTemplate().update("EB_SELLER_CATEGORY.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKeySelective(EbSellerCategory record) {
        int rows = getSqlMapClientTemplate().update("EB_SELLER_CATEGORY.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public List selectByExample(EbSellerCategoryExample example) {
        List list = getSqlMapClientTemplate().queryForList("EB_SELLER_CATEGORY.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbSellerCategory selectByPrimaryKey(EbSellerCategoryKey key) {
        EbSellerCategory record = (EbSellerCategory) getSqlMapClientTemplate().queryForObject("EB_SELLER_CATEGORY.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByExample(EbSellerCategoryExample example) {
        int rows = getSqlMapClientTemplate().delete("EB_SELLER_CATEGORY.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByPrimaryKey(EbSellerCategoryKey key) {
        int rows = getSqlMapClientTemplate().delete("EB_SELLER_CATEGORY.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int countByExample(EbSellerCategoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EB_SELLER_CATEGORY.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExampleSelective(EbSellerCategory record, EbSellerCategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_SELLER_CATEGORY.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExample(EbSellerCategory record, EbSellerCategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_SELLER_CATEGORY.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table EB_SELLER_CATEGORY
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    private static class UpdateByExampleParms extends EbSellerCategoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, EbSellerCategoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}