package com.ufgov.gk.server.ebay.dao;

import com.ufgov.gk.common.ebay.model.EbSite;
import com.ufgov.gk.common.ebay.model.EbSiteExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EbSiteDAOImpl extends SqlMapClientDaoSupport implements EbSiteDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbSiteDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public void insert(EbSite record) {
        getSqlMapClientTemplate().insert("EB_SITE.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKey(EbSite record) {
        int rows = getSqlMapClientTemplate().update("EB_SITE.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByPrimaryKeySelective(EbSite record) {
        int rows = getSqlMapClientTemplate().update("EB_SITE.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public List selectByExample(EbSiteExample example) {
        List list = getSqlMapClientTemplate().queryForList("EB_SITE.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public EbSite selectByPrimaryKey(String siteId) {
        EbSite key = new EbSite();
        key.setSiteId(siteId);
        EbSite record = (EbSite) getSqlMapClientTemplate().queryForObject("EB_SITE.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByExample(EbSiteExample example) {
        int rows = getSqlMapClientTemplate().delete("EB_SITE.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int deleteByPrimaryKey(String siteId) {
        EbSite key = new EbSite();
        key.setSiteId(siteId);
        int rows = getSqlMapClientTemplate().delete("EB_SITE.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int countByExample(EbSiteExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EB_SITE.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExampleSelective(EbSite record, EbSiteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_SITE.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    public int updateByExample(EbSite record, EbSiteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EB_SITE.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    private static class UpdateByExampleParms extends EbSiteExample {
        private Object record;

        public UpdateByExampleParms(Object record, EbSiteExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}