package com.ufgov.gk.server.ebay.dao;

import com.ufgov.gk.common.ebay.model.EbSite;
import com.ufgov.gk.common.ebay.model.EbSiteExample;
import java.util.List;

public interface EbSiteDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    void insert(EbSite record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByPrimaryKey(EbSite record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByPrimaryKeySelective(EbSite record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    List selectByExample(EbSiteExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    EbSite selectByPrimaryKey(String siteId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int deleteByExample(EbSiteExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int deleteByPrimaryKey(String siteId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int countByExample(EbSiteExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByExampleSelective(EbSite record, EbSiteExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EB_SITE
     *
     * @abatorgenerated Sat Jun 23 08:51:07 CST 2012
     */
    int updateByExample(EbSite record, EbSiteExample example);
}