package com.ufgov.gk.common.system.constants;

public interface ZcElementConstants {

  //EB_SITE
  String FIELD_EB_SITE_SITE_NAME = "SITE_NAME";

  String FIELD_EB_SITE_SITE_URL = "SITE_URL";

  String FIELD_EB_SITE_SITE_ID = "SITE_ID";

  //EB_APP_SERVER
  String FIELD_EB_APP_SERVER_SERVER_URL = "SERVER_URL";

  String FIELD_EB_APP_SERVER_EPS_SERVER_URL = "EPS_SERVER_URL";

  String FIELD_EB_APP_SERVER_SIGN_IN_URL = "SIGN_IN_URL";

  String FIELD_EB_APP_SERVER_SITE_ID = "SITE_ID";

  //EB_APP_ACCOUNT
  String FIELD_EB_APP_ACCOUNT_APP_ACCOUNT = "APP_ACCOUNT";

  String FIELD_EB_APP_ACCOUNT_APP_PASSWORD = "APP_PASSWORD";

  String FIELD_EB_APP_ACCOUNT_PRODUCTION_DEVID = "PRODUCTION_DEVID";

  String FIELD_EB_APP_ACCOUNT_PRODUCTION_APPID = "PRODUCTION_APPID";

  String FIELD_EB_APP_ACCOUNT_PRODUCTION_CERTID = "PRODUCTION_CERTID";

  String FIELD_EB_APP_ACCOUNT_PRODUCTION_TOKEN = "PRODUCTION_TOKEN";

  String FIELD_EB_APP_ACCOUNT_EBAY_ACCOUNT = "EBAY_ACCOUNT";

  String FIELD_EB_APP_ACCOUNT_CALL_LIMITATION = "CALL_LIMITATION";

  String FIELD_EB_APP_ACCOUNT_SANDBOX_DEVID = "SANDBOX_DEVID";

  String FIELD_EB_APP_ACCOUNT_SANDBOX_APPID = "SANDBOX_APPID";

  String FIELD_EB_APP_ACCOUNT_SANDBOX_CERTID = "SANDBOX_CERTID";

  String FIELD_EB_APP_ACCOUNT_SANDBOX_TOKEN = "SANDBOX_TOKEN";

  String FIELD_EB_APP_ACCOUNT_TOKEN_EXPIRE_TIME = "TOKEN_EXPIRE_TIME";

  //EB_ACCOUNT
  String FIELD_EB_ACCOUNT_EBAY_ACCOUNT = "EBAY_ACCOUNT";

  String FIELD_EB_ACCOUNT_EBAY_PASSWORD = "EBAY_PASSWORD";

  //EB_CATEGORY
  String FIELD_EB_CATEGORY_CATEGORY_ID = "CATEGORY_ID";

  String FIELD_EB_CATEGORY_CATEGORY_NAME = "CATEGORY_NAME";

  String FIELD_EB_CATEGORY_PARENT_ID = "PARENT_ID";

  String FIELD_EB_CATEGORY_PARENT_NAME = "PARENT_NAME";

  //EB_SELLER_GROUP
  String FIELD_EB_SELLER_GROUP_GROUP_ID = "GROUP_ID";

  String FIELD_EB_SELLER_GROUP_NAME = "NAME";

  String FIELD_EB_SELLER_GROUP_REMARK = "REMARK";

  //EB_CURRENCY
  String FIELD_EB_CURRENCY_CURRENCY_ID = "CURRENCY_ID";

  String FIELD_EB_CURRENCY_NAME = "NAME";

  String FIELD_EB_CURRENCY_EXCHANGE_RATE = "EXCHANGE_RATE";

  //EB_SELLER
  String FIELD_EB_SELLER_SELLER_ID = "SELLER_ID";

  String FIELD_EB_SELLER_CONTRY = "CONTRY";

  String FIELD_EB_SELLER_REGISTER_DATE = "REGISTER_DATE";

  String FIELD_EB_SELLER_FEEDBACK = "FEEDBACK";

  String FIELD_EB_SELLER_GROUP_ID = "GROUP_ID";

  String FIELD_EB_SELLER_CITY = "CITY";

  String FIELD_EB_SELLER_REMARK = "REMARK";

  String FIELD_EB_SELLER_IMAGE_SITE = "IMAGE_SITE";

  String FIELD_EB_SELLER_ATTENTION_STATUS = "ATTENTION_STATUS";

  //EB_ITEM
  String FIELD_EB_ITEM_ITEM_ID = "ITEM_ID";

  String FIELD_EB_ITEM_START_TIME = "START_TIME";

  String FIELD_EB_ITEM_END_TIME = "END_TIME";

  String FIELD_EB_ITEM_SOLD_QUALITY = "SOLD_QUALITY";

  String FIELD_EB_ITEM_PRICE = "PRICE";

  String FIELD_EB_ITEM_SHIPPING_TYPE = "SHIPPING_TYPE";

  String FIELD_EB_ITEM_SHIPPING_FEE = "SHIPPING_FEE";

  String FIELD_EB_ITEM_SELLING_PER_DAY = "SELLING_PER_DAY";

  String FIELD_EB_ITEM_SELLING_DAYS = "SELLING_DAYS";

  String FIELD_EB_ITEM_NAME = "NAME";

  String FIELD_EB_ITEM_URL = "URL";

  String FIELD_EB_ITEM_SELLER_ID = "SELLER_ID";

  String FIELD_EB_ITEM_IMAGE_URL = "IMAGE_URL";

  String FIELD_EB_ITEM_CURRENCY_ID = "CURRENCY_ID";

  String FIELD_EB_ITEM_SITE_ID = "SITE_ID";

  String FIELD_EB_ITEM_ITEMS = "ITEMS";

  String FIELD_EB_ITEM_BID_COUNT = "BID_COUNT";

  String FIELD_EB_ITEM_COUNTRY = "COUNTRY";

  String FIELD_EB_ITEM_CATEGORY_ID = "CATEGORY_ID";

  String FIELD_EB_ITEM_CATEGORY_NAME = "CATEGORY_NAME";

  String FIELD_EB_ITEM_LOCATION = "LOCATION";

  String FIELD_EB_ITEM_TIME_LEFT = "TIME_LEFT";

  String FIELD_EB_ITEM_SKU = "SKU";

  String FIELD_EB_ITEM_LISTING_TYPE = "LISTING_TYPE";

  String FIELD_EB_ITEM_CANDIDATE_STATUS = "CANDIDATE_STATUS";

  //EB_RETRIEVAL_TASK
  String FIELD_EB_RETRIEVAL_TASK_SELLER_ID = "SELLER_ID";

  String FIELD_EB_RETRIEVAL_TASK_TASK_START_TIME = "TASK_START_TIME";

  String FIELD_EB_RETRIEVAL_TASK_RETRIEVAL_TYPE = "RETRIEVAL_TYPE";

  String FIELD_EB_RETRIEVAL_TASK_SELLING_ITEM_QUALITY = "SELLING_ITEM_QUALITY";

  String FIELD_EB_RETRIEVAL_TASK_STATUS = "STATUS";

  String FIELD_EB_RETRIEVAL_TASK_TOTAL_ITEM_QUALITY = "TOTAL_ITEM_QUALITY";

  String FIELD_EB_RETRIEVAL_TASK_RETRIEVAL_ANCHOR_TIME = "RETRIEVAL_ANCHOR_TIME";

  String FIELD_EB_RETRIEVAL_TASK_STEP = "STEP";

  String FIELD_EB_RETRIEVAL_TASK_TIME_CONSUMING = "TIME_CONSUMING";

  String FIELD_EB_RETRIEVAL_TASK_RETRIEVAL_MONTHS = "RETRIEVAL_MONTHS";

  String FIELD_EB_RETRIEVAL_TASK_TOTAL_SOLD_AMOUNT = "TOTAL_SOLD_AMOUNT";

  String FIELD_EB_RETRIEVAL_TASK_TOTAL_SOLD_QUALITY = "TOTAL_SOLD_QUALITY";

  String FIELD_EB_RETRIEVAL_TASK_CREATE_TIME = "CREATE_TIME";

  String FIELD_EB_RETRIEVAL_TASK_GROUP_ID = "GROUP_ID";

  String FIELD_EB_RETRIEVAL_TASK_ANALYSE_STATUS = "ANALYSE_STATUS";

  String FIELD_EB_RETRIEVAL_TASK_ANALYSE_TIME = "ANALYSE_TIME";

  //EB_CANDIDATE_ITEM
  String FIELD_EB_CANDIDATE_ITEM_CANDIDATE_ID = "CANDIDATE_ID";

  String FIELD_EB_CANDIDATE_ITEM_CATEGORY_ID = "CATEGORY_ID";

  String FIELD_EB_CANDIDATE_ITEM_NAME = "NAME";

  String FIELD_EB_CANDIDATE_ITEM_WEIGHT = "WEIGHT";

  String FIELD_EB_CANDIDATE_ITEM_ITEM_SIZE = "ITEM_SIZE";

  String FIELD_EB_CANDIDATE_ITEM_TB_URL = "TB_URL";

  String FIELD_EB_CANDIDATE_ITEM_TB_PRICE = "TB_PRICE";

  String FIELD_EB_CANDIDATE_ITEM_TB_REMARK = "TB_REMARK";

  String FIELD_EB_CANDIDATE_ITEM_EB_URL = "EB_URL";

  String FIELD_EB_CANDIDATE_ITEM_EB_PRICE = "EB_PRICE";

  String FIELD_EB_CANDIDATE_ITEM_EB_SOLD_QUALITY = "EB_SOLD_QUALITY";

  String FIELD_EB_CANDIDATE_ITEM_EB_REMARK = "EB_REMARK";

  String FIELD_EB_CANDIDATE_ITEM_TB_SHIPPING_FEE = "TB_SHIPPING_FEE";

  String FIELD_EB_CANDIDATE_ITEM_REMARK = "REMARK";

  String FIELD_EB_CANDIDATE_ITEM_ITEM_ID = "ITEM_ID";

  String FIELD_EB_CANDIDATE_ITEM_STATUS = "STATUS";

  String FIELD_EB_CANDIDATE_ITEM_CURRENCY_ID = "CURRENCY_ID";

  String FIELD_EB_CANDIDATE_ITEM_TB_FULL_NAME = "TB_FULL_NAME";

  String FIELD_EB_CANDIDATE_ITEM_EB_FULL_NAME = "EB_FULL_NAME";

  String FIELD_EB_CANDIDATE_ITEM_EB_SHIPPING_FEE = "EB_SHIPPING_FEE";

  String FIELD_EB_CANDIDATE_ITEM_ALI_URL = "ALI_URL";

  String FIELD_EB_CANDIDATE_ITEM_ALI_PRICE = "ALI_PRICE";

  String FIELD_EB_CANDIDATE_ITEM_ALI_REMARK = "ALI_REMARK";

  String FIELD_EB_CANDIDATE_ITEM_EB_SITE = "EB_SITE";

  String FIELD_EB_CANDIDATE_ITEM_START_TIME = "START_TIME";

  String FIELD_EB_CANDIDATE_ITEM_END_TIME = "END_TIME";

  String FIELD_EB_CANDIDATE_ITEM_SELLING_DAYS = "SELLING_DAYS";

  String FIELD_EB_CANDIDATE_ITEM_IS_SELLING = "IS_SELLING";

  String FIELD_EB_CANDIDATE_ITEM_SELLING_PER_DAY = "SELLING_PER_DAY";

  String FIELD_EB_CANDIDATE_ITEM_COST = "COST";

  String FIELD_EB_CANDIDATE_ITEM_PROFIT = "PROFIT";

  String FIELD_EB_CANDIDATE_ITEM_PROFIT_RATE = "PROFIT_RATE";

  String FIELD_EB_CANDIDATE_ITEM_EB_IMAGE_URL = "EB_IMAGE_URL";

  String FIELD_EB_CANDIDATE_ITEM_TRANSPORT_MODE = "TRANSPORT_MODE";

  String FIELD_EB_CANDIDATE_ITEM_IMAGE_URL = "IMAGE_URL";

  String FIELD_EB_CANDIDATE_ITEM_TRANSPORT_FEE = "TRANSPORT_FEE";

  String FIELD_EB_CANDIDATE_ITEM_SKU = "SKU";
}
