package com.ufgov.gk.server.system.dao;

import com.ufgov.gk.common.system.model.AsMenuCompo;
import com.ufgov.gk.common.system.model.AsMenuCompoExample;
import com.ufgov.gk.common.system.model.AsMenuCompoKey;
import java.util.List;

public interface AsMenuCompoDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AS_MENU_COMPO
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    void insert(AsMenuCompo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AS_MENU_COMPO
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    int updateByPrimaryKey(AsMenuCompo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AS_MENU_COMPO
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    int updateByPrimaryKeySelective(AsMenuCompo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AS_MENU_COMPO
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    List selectByExample(AsMenuCompoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AS_MENU_COMPO
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    AsMenuCompo selectByPrimaryKey(AsMenuCompoKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AS_MENU_COMPO
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    int deleteByExample(AsMenuCompoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AS_MENU_COMPO
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    int deleteByPrimaryKey(AsMenuCompoKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AS_MENU_COMPO
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    int countByExample(AsMenuCompoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AS_MENU_COMPO
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    int updateByExampleSelective(AsMenuCompo record, AsMenuCompoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AS_MENU_COMPO
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    int updateByExample(AsMenuCompo record, AsMenuCompoExample example);
}