package com.ufgov.gk.server.system.dao;

import java.util.List;

import com.ufgov.zc.common.system.model.AsValset;
import com.ufgov.zc.common.system.model.AsValsetExample;

public interface AsValsetDAO {
  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table AS_VALSET
   *
   * @abatorgenerated Tue Jun 26 18:19:50 CST 2012
   */
  void insert(AsValset record);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table AS_VALSET
   *
   * @abatorgenerated Tue Jun 26 18:19:50 CST 2012
   */
  int updateByPrimaryKey(AsValset record);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table AS_VALSET
   *
   * @abatorgenerated Tue Jun 26 18:19:50 CST 2012
   */
  int updateByPrimaryKeySelective(AsValset record);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table AS_VALSET
   *
   * @abatorgenerated Tue Jun 26 18:19:50 CST 2012
   */
  List selectByExample(AsValsetExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table AS_VALSET
   *
   * @abatorgenerated Tue Jun 26 18:19:50 CST 2012
   */
  AsValset selectByPrimaryKey(String valsetId);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table AS_VALSET
   *
   * @abatorgenerated Tue Jun 26 18:19:50 CST 2012
   */
  int deleteByExample(AsValsetExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table AS_VALSET
   *
   * @abatorgenerated Tue Jun 26 18:19:50 CST 2012
   */
  int deleteByPrimaryKey(String valsetId);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table AS_VALSET
   *
   * @abatorgenerated Tue Jun 26 18:19:50 CST 2012
   */
  int countByExample(AsValsetExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table AS_VALSET
   *
   * @abatorgenerated Tue Jun 26 18:19:50 CST 2012
   */
  int updateByExampleSelective(AsValset record, AsValsetExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table AS_VALSET
   *
   * @abatorgenerated Tue Jun 26 18:19:50 CST 2012
   */
  int updateByExample(AsValset record, AsValsetExample example);

  List getAsValByValSql(String valSetId, String valSql);
}