package com.ufgov.gk.common.system.model;

import java.math.BigDecimal;

public class AsMenuCompo extends AsMenuCompoKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AS_MENU_COMPO.ORD_INDEX
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    private BigDecimal ordIndex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AS_MENU_COMPO.IS_GOTO_EDIT
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    private String isGotoEdit;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AS_MENU_COMPO.IS_IN_MENU
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    private String isInMenu;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AS_MENU_COMPO.IS_ALWAYS_NEW
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    private String isAlwaysNew;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AS_MENU_COMPO.URL
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    private String url;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AS_MENU_COMPO.ORD_INDEX
     *
     * @return the value of AS_MENU_COMPO.ORD_INDEX
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public BigDecimal getOrdIndex() {
        return ordIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AS_MENU_COMPO.ORD_INDEX
     *
     * @param ordIndex the value for AS_MENU_COMPO.ORD_INDEX
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public void setOrdIndex(BigDecimal ordIndex) {
        this.ordIndex = ordIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AS_MENU_COMPO.IS_GOTO_EDIT
     *
     * @return the value of AS_MENU_COMPO.IS_GOTO_EDIT
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public String getIsGotoEdit() {
        return isGotoEdit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AS_MENU_COMPO.IS_GOTO_EDIT
     *
     * @param isGotoEdit the value for AS_MENU_COMPO.IS_GOTO_EDIT
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public void setIsGotoEdit(String isGotoEdit) {
        this.isGotoEdit = isGotoEdit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AS_MENU_COMPO.IS_IN_MENU
     *
     * @return the value of AS_MENU_COMPO.IS_IN_MENU
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public String getIsInMenu() {
        return isInMenu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AS_MENU_COMPO.IS_IN_MENU
     *
     * @param isInMenu the value for AS_MENU_COMPO.IS_IN_MENU
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public void setIsInMenu(String isInMenu) {
        this.isInMenu = isInMenu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AS_MENU_COMPO.IS_ALWAYS_NEW
     *
     * @return the value of AS_MENU_COMPO.IS_ALWAYS_NEW
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public String getIsAlwaysNew() {
        return isAlwaysNew;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AS_MENU_COMPO.IS_ALWAYS_NEW
     *
     * @param isAlwaysNew the value for AS_MENU_COMPO.IS_ALWAYS_NEW
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public void setIsAlwaysNew(String isAlwaysNew) {
        this.isAlwaysNew = isAlwaysNew;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AS_MENU_COMPO.URL
     *
     * @return the value of AS_MENU_COMPO.URL
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AS_MENU_COMPO.URL
     *
     * @param url the value for AS_MENU_COMPO.URL
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public void setUrl(String url) {
        this.url = url;
    }
}