package com.ufgov.gk.common.system.model;

public class AsMenuCompoKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AS_MENU_COMPO.COMPO_ID
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    private String compoId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AS_MENU_COMPO.MENU_ID
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    private String menuId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AS_MENU_COMPO.COMPO_ID
     *
     * @return the value of AS_MENU_COMPO.COMPO_ID
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public String getCompoId() {
        return compoId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AS_MENU_COMPO.COMPO_ID
     *
     * @param compoId the value for AS_MENU_COMPO.COMPO_ID
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public void setCompoId(String compoId) {
        this.compoId = compoId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AS_MENU_COMPO.MENU_ID
     *
     * @return the value of AS_MENU_COMPO.MENU_ID
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AS_MENU_COMPO.MENU_ID
     *
     * @param menuId the value for AS_MENU_COMPO.MENU_ID
     *
     * @abatorgenerated Sat Jun 23 09:24:11 CST 2012
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
}